import path from "path";
import { parse as parseYaml } from "yaml";
import { getErrorMessage } from "../../utils/errors";
import { readFile, writeFile, ensureDir, glob, fileExists, copy } from "../../utils/fs";
import { log, verbose, warn } from "../../utils/logger";
import {
  generateSkillPluginManifest,
  writePluginManifest,
  getPluginManifestPath,
} from "../plugins";
import { parseFrontmatter } from "../loading";
import { computeSkillFolderHash, determinePluginVersion, writeContentHash } from "../versioning";
import type { PluginManifest, SkillFrontmatter } from "../../types";
import { formatZodIssues, skillMetadataLoaderSchema } from "../schemas";
import type { z } from "zod";

type SkillMetadata = z.infer<typeof skillMetadataLoaderSchema>;
import { DEFAULT_BRANDING, STANDARD_FILES } from "../../consts";
import { stripYamlSchemaComment } from "../../utils/yaml-schema";
import { SKILL_CONTENT_FILES, SKILL_CONTENT_DIRS } from "../metadata-keys";

export type SkillPluginOptions = {
  skillPath: string;
  outputDir: string;
  skillName?: string;
};

export type CompiledSkillPlugin = {
  pluginPath: string;
  manifest: PluginManifest;
  skillName: string;
};

export type SkillCompilationRun = {
  compiled: CompiledSkillPlugin[];
  /** Directory basenames of skills that failed to compile this run. */
  failed: string[];
};

function sanitizeSkillName(name: string): string {
  return name.replace(/\+/g, "-");
}

async function readSkillMetadata(skillPath: string): Promise<SkillMetadata | null> {
  const metadataPath = path.join(skillPath, STANDARD_FILES.METADATA_YAML);

  if (!(await fileExists(metadataPath))) {
    return null;
  }

  try {
    const content = await readFile(metadataPath);
    const { yamlContent } = stripYamlSchemaComment(content);

    const result = skillMetadataLoaderSchema.safeParse(parseYaml(yamlContent));
    if (!result.success) {
      warn(`Invalid metadata.yaml at '${skillPath}': ${formatZodIssues(result.error.issues)}`);
      return null;
    }
    return result.data;
  } catch (error) {
    warn(`Failed to read metadata.yaml at '${skillPath}': ${error}`);
    return null;
  }
}

function generateReadme(skillName: string, frontmatter: SkillFrontmatter): string {
  return `# ${skillName}

${frontmatter.description}

## Installation

Add this plugin to your Claude Code configuration:

\`\`\`json
{
  "plugins": ["${skillName}"]
}
\`\`\`

## Usage

This skill is automatically available when installed.

---

*Generated by ${DEFAULT_BRANDING.NAME} skill-plugin-compiler*
`;
}

export async function compileSkillPlugin(
  options: SkillPluginOptions,
): Promise<CompiledSkillPlugin> {
  const { skillPath, outputDir, skillName: overrideName } = options;

  const dirBasename = path.basename(skillPath);

  const skillMdPath = path.join(skillPath, STANDARD_FILES.SKILL_MD);
  if (!(await fileExists(skillMdPath))) {
    throw new Error(
      `Skill '${dirBasename}' is missing required ${STANDARD_FILES.SKILL_MD} file. Expected at: ${skillMdPath}`,
    );
  }

  const skillMdContent = await readFile(skillMdPath);
  const frontmatter = parseFrontmatter(skillMdContent, skillMdPath);

  if (!frontmatter) {
    throw new Error(
      `Skill '${dirBasename}' has invalid or missing YAML frontmatter in ${STANDARD_FILES.SKILL_MD}. ` +
        `Required fields: 'name' and 'description'. File: ${skillMdPath}`,
    );
  }

  const skillName = overrideName ?? sanitizeSkillName(frontmatter.name);

  verbose(`Compiling skill plugin: ${skillName} from ${skillPath}`);

  const metadata = await readSkillMetadata(skillPath);

  const pluginDir = path.join(outputDir, skillName);
  const skillsDir = path.join(pluginDir, "skills", skillName);

  await ensureDir(pluginDir);
  await ensureDir(skillsDir);

  const newHash = await computeSkillFolderHash(skillPath);

  const { version, contentHash } = await determinePluginVersion(
    newHash,
    pluginDir,
    getPluginManifestPath,
  );

  const manifest = generateSkillPluginManifest({
    skillName,
    description: frontmatter.description,
    author: metadata?.author,
    version,
  });

  await writePluginManifest(pluginDir, manifest);

  await writeContentHash(pluginDir, contentHash, getPluginManifestPath);

  verbose(`  Wrote plugin.json for ${skillName} (v${version})`);

  await writeFile(path.join(skillsDir, STANDARD_FILES.SKILL_MD), skillMdContent);
  verbose(`  Copied ${STANDARD_FILES.SKILL_MD}`);

  for (const fileName of SKILL_CONTENT_FILES) {
    if (fileName === STANDARD_FILES.SKILL_MD) continue;

    const sourcePath = path.join(skillPath, fileName);
    if (await fileExists(sourcePath)) {
      const content = await readFile(sourcePath);
      await writeFile(path.join(skillsDir, fileName), content);
      verbose(`  Copied ${fileName}`);
    }
  }

  for (const dirName of SKILL_CONTENT_DIRS) {
    const sourceDir = path.join(skillPath, dirName);
    if (await fileExists(sourceDir)) {
      await copy(sourceDir, path.join(skillsDir, dirName));
      verbose(`  Copied ${dirName}/`);
    }
  }

  const readme = generateReadme(skillName, frontmatter);
  await writeFile(path.join(pluginDir, STANDARD_FILES.README_MD), readme);
  verbose("  Generated README.md");

  return {
    pluginPath: pluginDir,
    manifest,
    skillName,
  };
}

export async function compileAllSkillPlugins(
  skillsDir: string,
  outputDir: string,
): Promise<SkillCompilationRun> {
  const compiled: CompiledSkillPlugin[] = [];
  const failed: string[] = [];

  const skillMdFiles = await glob(`**/${STANDARD_FILES.SKILL_MD}`, skillsDir);

  for (const skillMdFile of skillMdFiles) {
    const skillPath = path.join(skillsDir, path.dirname(skillMdFile));

    try {
      const result = await compileSkillPlugin({
        skillPath,
        outputDir,
      });
      compiled.push(result);
      log(`  [OK] ${result.skillName}`);
    } catch (error) {
      const errorMessage = getErrorMessage(error);
      const dirBasename = path.basename(skillPath);
      failed.push(dirBasename);
      warn(`Failed to compile skill from '${dirBasename}': ${errorMessage}`);
    }
  }

  return { compiled, failed };
}

export function printCompilationSummary(results: CompiledSkillPlugin[]): void {
  log(`\nCompiled ${results.length} skill plugins:`);
  for (const result of results) {
    log(`  - ${result.skillName} (v${result.manifest.version})`);
  }
}
