import path from "path";
import { z } from "zod";

import { DEFAULT_PLUGIN_NAME, PROJECT_ROOT } from "../../consts";
import { readFile } from "../../utils/fs";

/**
 * The provenance marker every compiled agent carries: an HTML comment on the first line
 * after the frontmatter, naming the generator, its version, and the fact that the file is
 * rewritten rather than edited.
 *
 * **A body comment, deliberately not a frontmatter field.** Claude Code documents sixteen
 * supported frontmatter keys and says nothing about how it treats an unknown one, so a
 * stricter release could reject every agent this CLI has ever written. The body is free-form
 * by contract, which makes a marker there safe, greppable, versioned, and the do-not-edit
 * notice at the same time.
 *
 * The version is informational — {@link hasProvenanceMarker} matches on the marker's SHAPE,
 * so an agent compiled by any release is recognised by any other. Matching the exact text
 * would sweep only the agents the running version happened to write.
 */
const MARKER_OPEN = `<!-- Generated by ${DEFAULT_PLUGIN_NAME} v`;
const MARKER_NOTICE = " — do not edit; compile rewrites this file";
const MARKER_CLOSE = " -->";

const FRONTMATTER_FENCE = "---";

const PACKAGE_JSON_FILE = "package.json";

/** The one field the marker needs from this CLI's own manifest. */
const ownPackageJsonSchema = z.object({ version: z.string().min(1) });

export function provenanceMarker(version: string): string {
  return `${MARKER_OPEN}${version}${MARKER_NOTICE}${MARKER_CLOSE}`;
}

/** Whether a line is a marker this CLI wrote, at any version and under any wording. */
function isProvenanceMarker(line: string): boolean {
  return line.startsWith(MARKER_OPEN) && line.endsWith(MARKER_CLOSE);
}

/**
 * The index of the first body line: past the closing frontmatter fence when there is one,
 * and the top of the file when there is not — a template override may render no frontmatter,
 * and the marker still needs a defined home.
 */
function bodyStartIndex(lines: readonly string[]): number {
  if (lines[0] !== FRONTMATTER_FENCE) return 0;
  const closingFence = lines.indexOf(FRONTMATTER_FENCE, 1);
  if (closingFence === -1) return 0;
  return closingFence + 1;
}

/**
 * Whether this CLI compiled the agent file this content came from.
 *
 * The marker's POSITION is part of the claim: an agent that merely quotes the line further
 * down (a prompt about this very feature, say) is the user's, and a sweep reading that as
 * provenance would delete a file nothing here wrote.
 */
export function hasProvenanceMarker(content: string): boolean {
  const lines = content.split("\n");
  const firstBodyLine = lines[bodyStartIndex(lines)];
  return firstBodyLine !== undefined && isProvenanceMarker(firstBodyLine);
}

/**
 * The same content carrying exactly one provenance marker, on the first line after the
 * frontmatter.
 *
 * Idempotent by replacement rather than by insertion: content that already carries a marker
 * has that line rewritten, so stamping twice at one version is a fixed point and a version
 * bump moves the line instead of stacking a second one beside it.
 */
export function stampProvenanceMarker(content: string, version: string): string {
  const lines = content.split("\n");
  const bodyStart = bodyStartIndex(lines);
  const replacedLines = hasProvenanceMarker(content) ? 1 : 0;

  return [
    ...lines.slice(0, bodyStart),
    provenanceMarker(version),
    ...lines.slice(bodyStart + replacedLines),
  ].join("\n");
}

let ownVersion: Promise<string> | undefined;

/**
 * This CLI's own published version, read once per process from the package manifest beside
 * the code — the same `PROJECT_ROOT` the bundled agent partials and templates resolve from,
 * so the version in a marker is the version of the compiler that wrote it.
 */
export function cliVersion(): Promise<string> {
  ownVersion ??= readOwnVersion();
  return ownVersion;
}

async function readOwnVersion(): Promise<string> {
  const manifestPath = path.join(PROJECT_ROOT, PACKAGE_JSON_FILE);
  const raw: unknown = JSON.parse(await readFile(manifestPath));

  const parsed = ownPackageJsonSchema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(`Could not read this CLI's own version from ${manifestPath}`);
  }
  return parsed.data.version;
}
