import path from "node:path";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { renderAgent } from "@workspace/compile/agent-source";

import { createLiquidEngine } from "../compiler.js";
import { createMockCompiledAgentData } from "../__tests__/factories/agent-factories.js";
import {
  cliVersion,
  hasProvenanceMarker,
  provenanceMarker,
  stampProvenanceMarker,
} from "./agent-provenance";

const CLI_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../..");

/** The shape the Liquid template renders: frontmatter, a blank line, then the body. */
const COMPILED_AGENT = [
  "---",
  "name: web-developer",
  "description: A test agent",
  "---",
  "",
  "# Web Developer Agent",
  "",
  "body",
].join("\n");

/** The same shape with no marker — what a user's own agent file looks like. */
const HAND_WRITTEN_AGENT = ["---", "name: my-custom-agent", "---", "", "# Mine"].join("\n");

const BODY_WITHOUT_FRONTMATTER = ["# Mine", "", "body"].join("\n");

/**
 * The marker as releases up to 0.162.0 spelled it — with the CLI's version inside the line.
 *
 * Stated as a literal rather than composed from the current builder, because the whole subject
 * is a shape this package no longer emits: a marker built from today's code could not go stale
 * against the files those releases wrote, which is exactly what the assertions below are for.
 */
const VERSIONED_MARKER_A_PAST_RELEASE_WROTE =
  "<!-- Generated by agents-inc v0.162.0 — do not edit; compile rewrites this file -->";

describe("agent provenance marker", () => {
  /**
   * A compiled agent IS a sub-agent's system prompt, so this line is the first cacheable byte
   * of every invocation of it. While the version lived here, a patch release rewrote that byte
   * in all eighteen agents and invalidated the prompt prefix beneath it — for a string no
   * production code ever read back. `hasProvenanceMarker` is the only production consumer and
   * it reads the marker's shape.
   */
  it("spells the same bytes whatever version stamped it", async () => {
    const pkg = JSON.parse(await readFile(path.join(CLI_ROOT, "package.json"), "utf8")) as {
      version: string;
    };

    expect(await cliVersion()).toBe(pkg.version);
    expect(
      provenanceMarker(),
      "the marker names a version again — every release now rewrites the first cacheable byte of all eighteen agents",
    ).not.toContain(pkg.version);
  });

  /**
   * The claim above is only that the marker itself does not name a version — it says nothing
   * about `agent.liquid` putting the version somewhere ELSE above the playbook, which
   * `stampProvenanceMarker` cannot see because it rewrites one fixed line and nothing else.
   * `grep -rn "Compiled by" --include="*.test.ts" packages/cli/src packages/compile/src`
   * returns nothing, so this is the render's own guard: two versions of the same agent must
   * produce byte-identical output up to `<system-reminder>`, and each must still carry its own
   * version somewhere inside it — a version dropped entirely would make the prefix check pass
   * for a reason that has nothing to do with where the version lives.
   */
  it("confines a version difference to the trailing <system-reminder> block", async () => {
    const engine = await createLiquidEngine();
    const data = createMockCompiledAgentData();

    const renderedAtV1 = await renderAgent(engine, data, "9.1.0");
    const renderedAtV2 = await renderAgent(engine, data, "9.2.0");

    const volatileBlockStart = "<system-reminder>";
    const prefix = (rendered: string) => rendered.slice(0, rendered.indexOf(volatileBlockStart));

    expect(
      prefix(renderedAtV1),
      "a version bump changed a byte above the trailing block, so it rewrites the cacheable prefix of every compiled agent again",
    ).toBe(prefix(renderedAtV2));
    expect(renderedAtV1).toContain("Compiled by 9.1.0.");
    expect(renderedAtV2).toContain("Compiled by 9.2.0.");
  });

  it("goes on the first line after the frontmatter", () => {
    expect(stampProvenanceMarker(COMPILED_AGENT)).toBe(
      [
        "---",
        "name: web-developer",
        "description: A test agent",
        "---",
        provenanceMarker(),
        "",
        "# Web Developer Agent",
        "",
        "body",
      ].join("\n"),
    );
  });

  it("goes on the first line when there is no frontmatter to follow", () => {
    expect(stampProvenanceMarker(BODY_WITHOUT_FRONTMATTER)).toBe(
      [provenanceMarker(), ...BODY_WITHOUT_FRONTMATTER.split("\n")].join("\n"),
    );
  });

  it("is a fixed point — stamping already-stamped content changes nothing", () => {
    const stamped = stampProvenanceMarker(COMPILED_AGENT);

    expect(stampProvenanceMarker(stamped)).toBe(stamped);
  });

  /**
   * The upgrade path, and the reason replacement stayed in `stampProvenanceMarker` after the
   * text became constant: every agent on every user's disk today carries the versioned line,
   * and a recompile has to leave exactly one marker behind rather than two.
   */
  it("replaces the versioned marker a past release wrote rather than stacking beside it", () => {
    const stampedByAPastRelease = [
      "---",
      "name: web-developer",
      "description: A test agent",
      "---",
      VERSIONED_MARKER_A_PAST_RELEASE_WROTE,
      "",
      "# Web Developer Agent",
      "",
      "body",
    ].join("\n");

    expect(stampProvenanceMarker(stampedByAPastRelease)).toBe(
      stampProvenanceMarker(COMPILED_AGENT),
    );
  });

  it("recognises its own marker and the versioned one a past release wrote", () => {
    expect(hasProvenanceMarker(stampProvenanceMarker(COMPILED_AGENT))).toBe(true);
    expect(
      hasProvenanceMarker(
        ["---", "name: a", "---", VERSIONED_MARKER_A_PAST_RELEASE_WROTE, "", "body"].join("\n"),
      ),
      "an agent a past release compiled is no longer recognised as this CLI's own — uninstall would leave it behind",
    ).toBe(true);
  });

  it("does not recognise an agent nothing stamped", () => {
    expect(hasProvenanceMarker(HAND_WRITTEN_AGENT)).toBe(false);
    expect(hasProvenanceMarker(BODY_WITHOUT_FRONTMATTER)).toBe(false);
  });

  /**
   * The marker's position is its contract — an agent that merely quotes the line further
   * down (a prompt about this very feature, say) was not compiled by this CLI, and a sweep
   * that read it as provenance would delete a file the user wrote.
   */
  it("does not recognise the marker quoted inside the body", () => {
    const quoting = [
      "---",
      "name: my-custom-agent",
      "---",
      "",
      "# Mine",
      "",
      `Compiled agents open with: ${provenanceMarker()}`,
    ].join("\n");

    expect(hasProvenanceMarker(quoting)).toBe(false);
  });
});
