import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import path from "path";
import { fileURLToPath } from "url";
import { mkdir, readFile, writeFile } from "fs/promises";

import {
  buildConfigTypesBackgroundData,
  generateConfigTypesSource,
  generateProjectConfigTypesSource,
  regenerateConfigTypes,
  type ConfigTypesBackgroundData,
} from "../config-types-writer";
import { createTempDir, cleanupTempDir } from "../../__tests__/test-fs-utils";
import { createMockSkill } from "../../__tests__/factories/skill-factories.js";
import { buildCategoryMap, createMockMatrix } from "../../__tests__/factories/matrix-factories.js";
import { createMockCategory } from "../../__tests__/factories/category-factories.js";
import {
  buildProjectConfig,
  buildAgentConfigs,
} from "../../__tests__/factories/config-factories.js";
import { buildSkillConfigs } from "../../__tests__/helpers/wizard-simulation.js";
import { SKILLS, TEST_CATEGORIES } from "../../__tests__/test-fixtures";
import {
  EMPTY_MATRIX,
  FULLSTACK_PAIR_MATRIX,
  SINGLE_REACT_MATRIX,
  SCSS_HONO_REACT_MATRIX,
  HONO_REACT_MATRIX,
} from "../../__tests__/mock-data/mock-matrices";
import { createMockAgent } from "../../__tests__/factories/agent-factories.js";
import { AGENT_DEFS } from "../../__tests__/mock-data/mock-agents.js";
import { CLAUDE_SRC_DIR, STANDARD_FILES } from "../../../consts";
import { generateConfigSource } from "../config-writer";
import { glob } from "../../../utils/fs";
import { bytewise } from "../../../utils/string";

import type {
  AgentDefinition,
  AgentName,
  CategoryDefinition,
  CategoryPath,
  SkillId,
  SkillSlug,
  Category,
} from "../../../types";

function makeBackgroundData(
  skills: Record<string, ReturnType<typeof createMockSkill>>,
  agentNames: AgentName[] = [],
  customAgentNames: AgentName[] = [],
): Promise<ConfigTypesBackgroundData> {
  return Promise.resolve({
    matrix: createMockMatrix(skills),
    agentNames,
    customAgentNames,
  });
}

/**
 * A locale whose collation orders two categories the catalogue actually ships against their code
 * units. Lithuanian places `y` immediately after `i`, so it puts `mobile-styling` before
 * `mobile-storage` where code units put it after — and `localeCompare` called with no locale
 * reads the process default, which Node takes from LC_ALL/LANG. So this is not a hypothetical
 * alphabet: it is what a project's committed config-types.ts becomes the first time it is
 * regenerated on a Lithuanian desktop.
 */
const DIVERGENT_COLLATION_LOCALE = "lt";

/** Skills in the two categories that locale reverses, stated in code-unit order. */
const COLLATION_DIVERGENT_SKILLS = {
  storage: createMockSkill("mobile-storage-mmkv"),
  styling: createMockSkill("mobile-styling-nativewind"),
};

describe("generateConfigTypesSource", () => {
  it("includes auto-generated header comment", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("// AUTO-GENERATED by agents-inc — DO NOT EDIT");
  });

  it("generates SkillId union from matrix skills", () => {
    const matrix = FULLSTACK_PAIR_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('"api-framework-hono"');
    expect(source).toContain('"web-framework-react"');
    expect(source).toContain("export type SkillId =");
  });

  it("generates AgentName union from provided agent names", () => {
    const matrix = EMPTY_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "api-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);
    expect(source).toContain('"api-developer"');
    expect(source).toContain('"web-developer"');
    expect(source).toContain("export type AgentName =");
  });

  it("sorts union members alphabetically", () => {
    const matrix = SCSS_HONO_REACT_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "api-developer", "cli-developer"];
    const source = generateConfigTypesSource(matrix, agentNames);

    // Verify skill IDs are sorted (api before web)
    const skillIdLine = source.split("\n").find((l) => l.startsWith("export type SkillId"));
    expect(skillIdLine).toContain("export type SkillId");
    const apiIdx = source.indexOf('"api-framework-hono"');
    const webFrameworkIdx = source.indexOf('"web-framework-react"');
    const webStylingIdx = source.indexOf('"web-styling-scss-modules"');
    expect(apiIdx).toBeLessThan(webFrameworkIdx);
    expect(webFrameworkIdx).toBeLessThan(webStylingIdx);

    // Verify agent names are sorted
    const apiDevIdx = source.indexOf('"api-developer"');
    const cliDevIdx = source.indexOf('"cli-developer"');
    const webDevIdx = source.indexOf('"web-developer"');
    expect(apiDevIdx).toBeLessThan(cliDevIdx);
    expect(cliDevIdx).toBeLessThan(webDevIdx);
  });

  it("generates Domain type from matrix categories", () => {
    const categories = buildCategoryMap({
      "web-framework": TEST_CATEGORIES.framework,
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api" },
    });

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type Domain = "api" | "web";');
  });

  it("generates Category union from matrix category keys", () => {
    const categories = buildCategoryMap({
      "web-framework": TEST_CATEGORIES.framework,
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api" },
      "web-styling": TEST_CATEGORIES.styling,
    });

    const matrix = createMockMatrix({}, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type Category = "api-api" | "web-framework" | "web-styling";');
  });

  it("emits never for empty categories", () => {
    const matrix = createMockMatrix({}, { categories: buildCategoryMap({}) });
    const source = generateConfigTypesSource(matrix, []);
    expect(source, "an empty category union must accept no category, not every string").toContain(
      "export type Category = never;",
    );
  });

  it("generates InstallMode type", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('export type InstallMode = "eject" | "plugin" | "mixed";');
  });

  it("generates generic SkillAssignment type with default type parameter", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain(
      "export type SkillAssignment<S extends SkillId = SkillId> = S | { id: S; preloaded: boolean };",
    );
  });

  /**
   * These two interfaces are emitted as literal TEXT into every user's
   * `.claude-src/config-types.ts`, which is what their own `config.ts` is checked against. A
   * field renamed in the type but not here type-errors the file the CLI just wrote.
   */
  it("declares a skill entry's provenance as origin", () => {
    const source = generateConfigTypesSource(EMPTY_MATRIX, []);

    expect(source).toContain("export type SkillConfig = {");
    expect(source).toContain("  origin: string;");
    expect(source).not.toContain("  source: string;");
  });

  it("declares the marketplace ref and the marketplace name on ProjectConfig", () => {
    const source = generateConfigTypesSource(EMPTY_MATRIX, []);

    expect(source).toContain("  marketplace?: string;");
    expect(source).toContain("  marketplaceName?: string;");
    expect(source).not.toContain("  source?: string;");
  });

  it("falls back to loose StackAgentConfig when no categories have skills", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    // Project configs always get the loose line, and they carry bare entries for exclusive
    // categories — so the loose line has to admit a single assignment as well as an array.
    expect(source).toContain(
      "export type StackAgentConfig = Partial<Record<Category, SkillAssignment | SkillAssignment[]>>;",
    );
  });

  it("generates a bare (unwrapped) property for an exclusive category", () => {
    const categories = buildCategoryMap({
      "web-framework": { ...TEST_CATEGORIES.framework, exclusive: true },
    });
    const matrix = createMockMatrix(SKILLS.react, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('  "web-framework"?: SkillAssignment<"web-framework-react">;');
    expect(source).toContain("};");
  });

  it("generates per-category StackAgentConfig, arrays only for non-exclusive categories", () => {
    const categories = buildCategoryMap({
      "web-framework": { ...TEST_CATEGORIES.framework, exclusive: true },
      "web-styling": { ...TEST_CATEGORIES.styling, exclusive: false },
      "api-api": { ...TEST_CATEGORIES.api, displayName: "API", domain: "api", exclusive: true },
    });
    const matrix = createMockMatrix(SKILLS.react, SKILLS.scss, SKILLS.hono, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('  "api-api"?: SkillAssignment<"api-framework-hono">;');
    expect(source).toContain('  "web-framework"?: SkillAssignment<"web-framework-react">;');
    expect(source).toContain('  "web-styling"?: SkillAssignment<"web-styling-scss-modules">[];');
  });

  it("names a category pair that locale's collation orders against their code units", () => {
    const lithuanian = new Intl.Collator(DIVERGENT_COLLATION_LOCALE);
    const { storage, styling } = COLLATION_DIVERGENT_SKILLS;

    expect(bytewise(storage.category, styling.category)).toBe(-1);
    expect(Math.sign(lithuanian.compare(storage.category, styling.category))).toBe(1);
  });

  it("orders StackAgentConfig keys by code unit, whatever collation the machine defaults to", () => {
    const { storage, styling } = COLLATION_DIVERGENT_SKILLS;
    const matrix = createMockMatrix(storage, styling);
    const config = buildProjectConfig({ skills: buildSkillConfigs([storage.id, styling.id]) });

    // Stands in for a machine whose default collation is Lithuanian, which is the only thing
    // `localeCompare` with no locale argument consults.
    const lithuanian = new Intl.Collator(DIVERGENT_COLLATION_LOCALE);
    const defaultCollation = vi
      .spyOn(String.prototype, "localeCompare")
      .mockImplementation(function (this: string, that: string) {
        return lithuanian.compare(String(this), that);
      });

    const collationInForce = Math.sign(storage.category.localeCompare(styling.category));
    const source = generateConfigTypesSource(matrix, [], [], undefined, config);
    defaultCollation.mockRestore();

    expect(
      collationInForce,
      "the stand-in must actually answer for the process default, or this spec proves nothing",
    ).toBe(1);
    expect(source).toContain(
      [
        "export type StackAgentConfig = {",
        `  "${storage.category}"?: SkillAssignment<"${storage.id}">[];`,
        `  "${styling.category}"?: SkillAssignment<"${styling.id}">[];`,
        "};",
      ].join("\n"),
    );
  });

  it("generates multi-line union for categories with more than 3 skills", () => {
    const categories = buildCategoryMap({
      "web-framework": { ...TEST_CATEGORIES.framework, exclusive: false },
    });
    const matrix = createMockMatrix(
      createMockSkill("web-framework-react"),
      createMockSkill("web-framework-vue-composition-api"),
      // Boundary casts: fictional skill IDs for testing multi-line union generation
      createMockSkill("web-framework-original" as SkillId),
      createMockSkill("web-framework-simple" as SkillId),
      { categories },
    );
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain('  "web-framework"?: SkillAssignment<');
    expect(source).toContain('    | "web-framework-original"');
    expect(source).toContain('    | "web-framework-react"');
    expect(source).toContain('    | "web-framework-simple"');
    expect(source).toContain('    | "web-framework-vue-composition-api"');
    expect(source).toContain("  >[];");
  });

  it("generates multi-line union without the array wrapper for an exclusive category", () => {
    const categories = buildCategoryMap({
      "web-framework": { ...TEST_CATEGORIES.framework, exclusive: true },
    });
    const matrix = createMockMatrix(
      createMockSkill("web-framework-react"),
      createMockSkill("web-framework-vue-composition-api"),
      // Boundary casts: fictional skill IDs for testing multi-line union generation
      createMockSkill("web-framework-original" as SkillId),
      createMockSkill("web-framework-simple" as SkillId),
      { categories },
    );
    const source = generateConfigTypesSource(matrix, []);
    // The union is over which skill may be assigned; exclusivity is about how many, so a long
    // candidate list still yields one assignment.
    expect(source).toContain('  "web-framework"?: SkillAssignment<');
    expect(source).toContain("  >;");
    expect(source).not.toContain("  >[];");
  });

  it("omits categories that have no matching skills from StackAgentConfig", () => {
    const categories = buildCategoryMap({
      "web-framework": TEST_CATEGORIES.framework,
      "web-styling": TEST_CATEGORIES.styling,
    });
    // Only add a React skill (web-framework), no styling skills
    const matrix = createMockMatrix(SKILLS.react, { categories });
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type StackAgentConfig = {");
    expect(source).toContain('"web-framework"?:');
    expect(source).not.toContain('"web-styling"?:');
  });

  it("generates ProjectConfig interface with ProjectAgentName stack keys", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export interface ProjectConfig {");
    expect(source).toContain("name: string;");
    expect(source).toContain("agents: AgentScopeConfig[];");
    expect(source).toContain("skills: SkillConfig[];");
    expect(source).toContain("stack?: Partial<Record<ProjectAgentName, StackAgentConfig>>;");
    expect(source).toContain("selectedDomains?: Domain[];");
    expect(source, "the active agents list is the only record of who is selected").not.toContain(
      "selectedAgents",
    );
    expect(source).toContain("marketplace?: string;");
    expect(source).toContain("marketplaceName?: string;");
    expect(source).toContain("agentsSource?: string;");
    expect(source).toContain("author?: string;");
    expect(source).toContain("description?: string;");
  });

  it("generates SelectedAgentName = AgentName for standalone config without config param", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source).toContain("export type SelectedAgentName = AgentName;");
  });

  it("generates ProjectAgentName = SelectedAgentName for global config", () => {
    const matrix = SINGLE_REACT_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "web-researcher"];
    const config = buildProjectConfig({
      agents: buildAgentConfigs(["web-developer", "web-researcher"], { scope: "global" }),
    });
    const source = generateConfigTypesSource(matrix, agentNames, [], undefined, config);
    expect(source).toContain("export type ProjectAgentName = SelectedAgentName;");
  });

  it("generates ProjectAgentName narrowed to project-scoped agents", () => {
    const matrix = SINGLE_REACT_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "web-researcher", "api-developer"];
    const config = buildProjectConfig({
      agents: [
        ...buildAgentConfigs(["web-developer"], { scope: "global" }),
        ...buildAgentConfigs(["web-researcher", "api-developer"], { scope: "project" }),
      ],
    });
    const source = generateConfigTypesSource(matrix, agentNames, [], undefined, config);
    expect(source).toContain('export type ProjectAgentName = "web-researcher" | "api-developer"');
    expect(source).not.toContain("export type ProjectAgentName = SelectedAgentName");
  });

  it("narrows SelectedAgentName to the config's non-excluded agents", () => {
    const matrix = SINGLE_REACT_MATRIX;
    const agentNames: AgentName[] = ["web-developer", "web-researcher", "api-developer"];
    const config = buildProjectConfig({
      agents: [
        ...buildAgentConfigs(["web-developer"], { scope: "global" }),
        ...buildAgentConfigs(["web-researcher"], { scope: "project" }),
        ...buildAgentConfigs(["api-developer"], { scope: "project", excluded: true }),
      ],
    });
    const source = generateConfigTypesSource(matrix, agentNames, [], undefined, config);
    expect(source).toContain('export type SelectedAgentName = "web-developer" | "web-researcher";');
  });

  it("emits never for empty skills", () => {
    const matrix = EMPTY_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source, "an empty skill union must accept no skill id, not every string").toContain(
      "export type SkillId = never;",
    );
  });

  it("emits never for empty agents", () => {
    const matrix = SINGLE_REACT_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    expect(source, "an empty agent union must accept no agent name, not every string").toContain(
      "export type AgentName = never;",
    );
  });

  it("emits never for empty domains", () => {
    const matrix = createMockMatrix(SKILLS.react, {
      categories: buildCategoryMap({}),
    });
    const source = generateConfigTypesSource(matrix, []);
    expect(source, "an empty domain union must accept no domain, not every string").toContain(
      "export type Domain = never;",
    );
  });

  it("uses single-line format for 5 or fewer union members", () => {
    const matrix = HONO_REACT_MATRIX;
    const source = generateConfigTypesSource(matrix, []);
    // 2 skills = single-line union
    expect(source).toContain('export type SkillId = "api-framework-hono" | "web-framework-react";');
  });

  it("uses multi-line format for 6 or more union members", () => {
    const ids = [
      "api-database-drizzle",
      "api-framework-hono",
      "web-framework-react",
      "web-framework-vue-composition-api",
      "web-state-zustand",
      "web-styling-scss-modules",
    ] as const;
    const matrix = createMockMatrix(
      ...ids.map((id) => createMockSkill(id, { category: "web-framework" })),
    );
    const source = generateConfigTypesSource(matrix, []);
    // 6 skills = multi-line union with leading pipes
    expect(source).toContain('  | "api-database-drizzle"');
    expect(source).toContain('  | "web-styling-scss-modules"');
  });

  describe("sectioned unions with custom and marketplace comments", () => {
    it("shows custom skills first with section comments", () => {
      // Boundary cast: custom skill IDs may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const acmeAudit = "acme-audit-runner" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, {
          category: "web-framework",
          slug: "deploy-pipeline" as SkillSlug,
          custom: true,
        }),
        createMockSkill(acmeAudit, {
          category: "web-framework",
          slug: "audit-runner" as SkillSlug,
          custom: true,
        }),
        SKILLS.react,
        SKILLS.scss,
      );
      const source = generateConfigTypesSource(matrix, []);

      // Custom skills appear first with comment
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      // Verify ordering: custom before marketplace
      const customIdx = source.indexOf("// Custom");
      const marketplaceIdx = source.indexOf("// Marketplace");
      expect(customIdx).toBeLessThan(marketplaceIdx);

      // Verify custom skills are in the custom section
      const acmeDeployIdx = source.indexOf('"acme-deploy-pipeline"');
      const acmeAuditIdx = source.indexOf('"acme-audit-runner"');
      expect(acmeAuditIdx).toBeGreaterThan(customIdx);
      expect(acmeAuditIdx).toBeLessThan(marketplaceIdx);
      expect(acmeDeployIdx).toBeGreaterThan(customIdx);
      expect(acmeDeployIdx).toBeLessThan(marketplaceIdx);

      // Marketplace skills appear after the marketplace comment
      const reactIdx = source.indexOf('"web-framework-react"');
      const scssIdx = source.indexOf('"web-styling-scss-modules"');
      expect(reactIdx).toBeGreaterThan(marketplaceIdx);
      expect(scssIdx).toBeGreaterThan(marketplaceIdx);
    });

    it("treats extra skill IDs as custom", () => {
      const matrix = SINGLE_REACT_MATRIX;
      // Boundary cast: extra skill ID may not match built-in SkillId prefix patterns
      const source = generateConfigTypesSource(matrix, [], [], {
        extraSkillIds: ["acme-deploy-pipeline"],
      });
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const extraIdx = source.indexOf('"acme-deploy-pipeline"');
      expect(extraIdx).toBeGreaterThan(customIdx);
    });

    it("leaves a declared skill out of the custom section when it arrives as an extra", () => {
      const matrix = FULLSTACK_PAIR_MATRIX;
      const source = generateConfigTypesSource(matrix, [], [], {
        extraSkillIds: ["web-framework-react"],
      });

      const skillStart = source.indexOf("export type SkillId =");
      const skillEnd = source.indexOf(";", skillStart);
      const skillSection = source.slice(skillStart, skillEnd);

      expect(skillSection).not.toContain("// Custom");
      expect(skillSection).toContain('"web-framework-react"');
    });

    it("omits comments when no custom skills exist", () => {
      const matrix = FULLSTACK_PAIR_MATRIX;
      const source = generateConfigTypesSource(matrix, []);
      expect(source).not.toContain("// Custom");
      expect(source).not.toContain("// Marketplace");
    });

    it("shows only Custom header when all skills are custom", () => {
      // Boundary cast: custom skill IDs may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const acmeAudit = "acme-audit-runner" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, {
          category: "web-framework",
          slug: "deploy-pipeline" as SkillSlug,
          custom: true,
        }),
        createMockSkill(acmeAudit, {
          category: "web-framework",
          slug: "audit-runner" as SkillSlug,
          custom: true,
        }),
      );
      const source = generateConfigTypesSource(matrix, []);
      expect(source).toContain("// Custom");
      expect(source).not.toContain("// Marketplace");
    });

    it("shows section comments for custom agent names", () => {
      const matrix = EMPTY_MATRIX;
      const agentNames: AgentName[] = ["api-developer", "web-developer"];
      // Boundary cast: custom agent name not in built-in AgentName union
      const customAgentNames = ["acme-deployer"] as unknown as AgentName[];
      const source = generateConfigTypesSource(
        matrix,
        [...agentNames, ...customAgentNames],
        customAgentNames,
      );
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const marketplaceIdx = source.indexOf("// Marketplace");
      const acmeIdx = source.indexOf('"acme-deployer"');
      expect(acmeIdx).toBeGreaterThan(customIdx);
      expect(acmeIdx).toBeLessThan(marketplaceIdx);
    });

    it("treats extra agent names as custom", () => {
      const matrix = EMPTY_MATRIX;
      const agentNames: AgentName[] = ["web-developer"];
      // Boundary cast: extra agent name may not match built-in AgentName union
      const source = generateConfigTypesSource(matrix, agentNames, [], {
        extraAgentNames: ["custom-agent"],
      });
      expect(source).toContain("// Custom");
      expect(source).toContain("// Marketplace");

      const customIdx = source.indexOf("// Custom");
      const customAgentIdx = source.indexOf('"custom-agent"');
      expect(customAgentIdx).toBeGreaterThan(customIdx);
    });

    it("leaves a declared agent out of the custom section when it arrives as an extra", () => {
      const matrix = EMPTY_MATRIX;
      const agentNames: AgentName[] = ["api-developer", "web-developer"];
      const source = generateConfigTypesSource(matrix, agentNames, [], {
        extraAgentNames: ["web-developer"],
      });

      const agentStart = source.indexOf("export type AgentName =");
      const agentEnd = source.indexOf(";", agentStart);
      const agentSection = source.slice(agentStart, agentEnd);

      expect(agentSection).not.toContain("// Custom");
      expect(agentSection).toContain('"web-developer"');
    });

    it("leaves a declared domain out of the custom section when it arrives as an extra", () => {
      const categories = buildCategoryMap({ "web-framework": TEST_CATEGORIES.framework });
      const matrix = createMockMatrix(SKILLS.react, { categories });
      const source = generateConfigTypesSource(matrix, [], [], { extraDomains: ["web"] });

      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).not.toContain("// Custom");
      expect(domainSection).toContain('"web"');
    });

    it("labels nothing custom when the extras name the whole configuration", () => {
      const categories = buildCategoryMap({
        "web-framework": TEST_CATEGORIES.framework,
        "api-api": { ...TEST_CATEGORIES.api, domain: "api" },
      });
      const matrix = createMockMatrix(SKILLS.react, SKILLS.hono, { categories });
      const agentNames: AgentName[] = ["api-developer", "web-developer"];

      const source = generateConfigTypesSource(matrix, agentNames, [], {
        extraSkillIds: ["api-framework-hono", "web-framework-react"],
        extraAgentNames: ["api-developer", "web-developer"],
        extraDomains: ["api", "web"],
        extraCategories: ["api-api", "web-framework"],
      });

      expect(source).not.toContain("// Custom");
    });

    it("leaves a declared category out of the custom section when a custom skill sits in it", () => {
      // Boundary cast: custom skill/category IDs may not match built-in prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "acme-deploy": createMockCategory("acme-deploy", "Deploy", {
          domain: "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, {
          category: "acme-deploy" as CategoryPath,
          slug: "deploy-pipeline" as SkillSlug,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      const categoryStart = source.indexOf("export type Category =");
      const categoryEnd = source.indexOf(";", categoryStart);
      const categorySection = source.slice(categoryStart, categoryEnd);

      // Both categories are the catalogue's — it declares them — however custom their skills are.
      expect(categorySection).not.toContain("// Custom");
      expect(categorySection).toContain('"acme-deploy"');
      expect(categorySection).toContain('"web-framework"');
    });

    it("leaves a declared category out of the custom section when it arrives as an extra", () => {
      const categories = buildCategoryMap({
        "web-framework": TEST_CATEGORIES.framework,
        "web-styling": TEST_CATEGORIES.styling,
      });
      const matrix = createMockMatrix(SKILLS.react, SKILLS.scss, { categories });
      const source = generateConfigTypesSource(matrix, [], [], {
        extraCategories: ["web-framework", "web-styling"],
      });

      const categoryStart = source.indexOf("export type Category =");
      const categoryEnd = source.indexOf(";", categoryStart);
      const categorySection = source.slice(categoryStart, categoryEnd);

      expect(categorySection).not.toContain("// Custom");
      expect(categorySection).toContain('"web-framework"');
    });

    it("marks a category no declaration covers as custom", () => {
      const categories = buildCategoryMap({ "web-framework": TEST_CATEGORIES.framework });
      const matrix = createMockMatrix(SKILLS.react, { categories });
      const source = generateConfigTypesSource(matrix, [], [], {
        extraCategories: ["acme-deploy"],
      });

      const categoryStart = source.indexOf("export type Category =");
      const categoryEnd = source.indexOf(";", categoryStart);
      const categorySection = source.slice(categoryStart, categoryEnd);

      expect(categorySection).toContain("// Custom");
      expect(categorySection).toContain("// Marketplace");
      const customIdx = categorySection.indexOf("// Custom");
      const marketplaceIdx = categorySection.indexOf("// Marketplace");
      expect(categorySection.indexOf('"acme-deploy"')).toBeGreaterThan(customIdx);
      expect(categorySection.indexOf('"acme-deploy"')).toBeLessThan(marketplaceIdx);
      expect(categorySection.indexOf('"web-framework"')).toBeGreaterThan(marketplaceIdx);
    });

    it("does not mark a domain custom because a custom skill's category carries it", () => {
      // Boundary cast: custom skill/category/domain not in built-in unions
      const acmeCi = "acme-ci-runner" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "devops-ci": createMockCategory("devops-ci", "CI/CD", {
          domain: "devops" as "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeCi, {
          category: "devops-ci" as CategoryPath,
          slug: "ci-runner" as SkillSlug,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).not.toContain("// Custom");
      expect(domainSection).toContain('"devops"');
      expect(domainSection).toContain('"web"');
    });

    it("treats extra domains as custom", () => {
      const categories = buildCategoryMap({ "web-framework": TEST_CATEGORIES.framework });
      const matrix = createMockMatrix(SKILLS.react, { categories });
      const source = generateConfigTypesSource(matrix, [], [], { extraDomains: ["devops"] });

      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).toContain("// Custom");
      expect(domainSection).toContain("// Marketplace");
      const customIdx = domainSection.indexOf("// Custom");
      const marketplaceIdx = domainSection.indexOf("// Marketplace");
      expect(domainSection.indexOf('"devops"')).toBeGreaterThan(customIdx);
      expect(domainSection.indexOf('"devops"')).toBeLessThan(marketplaceIdx);
    });

    it("does not mark domain as custom if it appears on both custom and non-custom categories", () => {
      // Boundary cast: custom skill/category key not in built-in unions
      const acmeTool = "acme-web-tool" as SkillId;
      const categories = {
        "web-framework": TEST_CATEGORIES.framework,
        "web-custom-tool": createMockCategory("web-custom-tool", "Custom Tool", {
          domain: "web",
        }),
      } as unknown as Record<Category, CategoryDefinition>;

      const matrix = createMockMatrix(
        createMockSkill(acmeTool, {
          category: "web-custom-tool" as CategoryPath,
          slug: "web-tool" as SkillSlug,
          custom: true,
        }),
        { categories },
      );
      const source = generateConfigTypesSource(matrix, []);

      // "web" domain appears on both custom and non-custom categories, so no section comments
      const domainStart = source.indexOf("export type Domain =");
      const domainEnd = source.indexOf(";", domainStart);
      const domainSection = source.slice(domainStart, domainEnd);

      expect(domainSection).not.toContain("// Custom");
      expect(domainSection).not.toContain("// Marketplace");
    });

    it("uses multi-line format when section comments are present even with few members", () => {
      // Boundary cast: custom skill ID may not match built-in SkillId prefix patterns
      const acmeDeploy = "acme-deploy-pipeline" as SkillId;
      const matrix = createMockMatrix(
        createMockSkill(acmeDeploy, {
          category: "web-framework",
          slug: "deploy-pipeline" as SkillSlug,
          custom: true,
        }),
        SKILLS.react,
      );
      const source = generateConfigTypesSource(matrix, []);

      // Even with just 2 members, section comments force multi-line format
      expect(source).toContain('  | "acme-deploy-pipeline"');
      expect(source).toContain('  | "web-framework-react"');
    });
  });
});

describe("regenerateConfigTypes", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir("cc-regen-types-test-");
  });

  afterEach(async () => {
    await cleanupTempDir(tempDir);
  });

  it("writes config-types.ts when .claude-src/ exists", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain("// AUTO-GENERATED by agents-inc");
    expect(content).toContain('"web-framework-react"');
  });

  it("creates .claude-src/ and writes config-types.ts when data is provided", async () => {
    // When background data is non-null, writeFile creates directories as needed
    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(tempDir, CLAUDE_SRC_DIR, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"web-framework-react"');
  });

  it("includes extra skill IDs in the generated output", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data, {
      extraSkillIds: ["acme-deploy-pipeline"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"acme-deploy-pipeline"');
    expect(content).toContain('"web-framework-react"');
  });

  it("does not duplicate extra skill IDs already in the matrix", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data, {
      extraSkillIds: ["web-framework-react"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    const matches = content.match(/"web-framework-react"/g);
    // Should appear in SkillId union only once (plus possibly in other type references)
    expect(matches).not.toBeNull();
    expect(matches!.length).toBeGreaterThanOrEqual(1);
  });

  it("includes extra agent names in the generated output", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({}, ["web-developer"]);

    await regenerateConfigTypes(tempDir, data, {
      extraAgentNames: ["custom-agent"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    expect(content).toContain('"custom-agent"');
    expect(content).toContain('"web-developer"');
  });

  it("does not duplicate extra agent names already in the data", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });

    const data = makeBackgroundData({}, ["web-developer"]);

    await regenerateConfigTypes(tempDir, data, {
      extraAgentNames: ["web-developer"],
    });

    const configTypesPath = path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");
    // Count occurrences of "web-developer" in the AgentName union section
    // (may span multiple lines due to section comments)
    const agentSectionStart = content.indexOf("export type AgentName =");
    const agentSectionEnd = content.indexOf(";", agentSectionStart);
    const agentSection = content.slice(agentSectionStart, agentSectionEnd);
    const matches = agentSection.match(/"web-developer"/g);
    expect(matches).toHaveLength(1);
  });

  it("propagates errors when background data promise rejects", async () => {
    const failingData = Promise.reject(new Error("Network error"));
    // Prevent unhandled rejection warning
    failingData.catch(() => {});

    await expect(regenerateConfigTypes(tempDir, failingData)).rejects.toThrow("Network error");
  });
});

describe("generateProjectConfigTypesSource", () => {
  it("generates import statement from global config-types", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("// AUTO-GENERATED by agents-inc — DO NOT EDIT");
    expect(source).toContain('from "../../.claude-src/config-types"');
    expect(source).toContain("SkillId as GlobalSkillId");
    expect(source).toContain("AgentName as GlobalAgentName");
    expect(source).toContain("Domain as GlobalDomain");
    expect(source).toContain("Category as GlobalCategory");
  });

  it("extends global types with project-only skill IDs", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["acme-deploy-pipeline"],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain('export type SkillId = GlobalSkillId | "acme-deploy-pipeline"');
  });

  it("extends global types with project-only agent names", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: ["custom-reviewer"],
      projectDomains: [],
    });
    expect(source).toContain('export type AgentName = GlobalAgentName | "custom-reviewer"');
  });

  it("extends global types with project-only domains", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: ["devops"],
    });
    expect(source).toContain('export type Domain = GlobalDomain | "devops"');
  });

  it("uses bare global type when no project members exist", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type SkillId = GlobalSkillId;");
    expect(source).toContain("export type AgentName = GlobalAgentName;");
    expect(source).toContain("export type Domain = GlobalDomain;");
    expect(source).toContain("export type Category = GlobalCategory;");
  });

  it("generates SelectedAgentName for project config with selectedAgentNames", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: ["custom-reviewer", "project-deployer"],
      projectDomains: [],
      selectedAgentNames: ["custom-reviewer", "project-deployer"],
    });
    expect(source).toContain(
      'export type SelectedAgentName = "custom-reviewer" | "project-deployer";',
    );
  });

  it("generates SelectedAgentName = AgentName for project config without selectedAgentNames", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type SelectedAgentName = AgentName;");
  });

  it("re-exports GlobalCategory when no project categories exist", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export type Category = GlobalCategory;");
    expect(source).toContain("Category as GlobalCategory");
  });

  it("extends GlobalCategory with project-specific categories", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
      projectCategories: ["custom-tooling"],
    });
    expect(source).toContain('export type Category = GlobalCategory | "custom-tooling"');
    expect(source).toContain("Category as GlobalCategory");
  });

  it("includes ProjectConfig interface template", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: [],
      projectAgentNames: [],
      projectDomains: [],
    });
    expect(source).toContain("export interface ProjectConfig {");
    expect(source).toContain('export type InstallMode = "eject" | "plugin" | "mixed"');
  });

  it("sorts multiple project members alphabetically", () => {
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["z-custom-tool", "a-custom-tool"],
      projectAgentNames: [],
      projectDomains: [],
    });
    const aIdx = source.indexOf('"a-custom-tool"');
    const zIdx = source.indexOf('"z-custom-tool"');
    expect(aIdx).toBeLessThan(zIdx);
  });

  it("extends global types when all items are global-scoped (full config passed)", () => {
    // When writeProjectConfigTypes receives the full config instead of just project split,
    // global-scoped items should appear as explicit union extensions
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["web-framework-react", "web-testing-vitest"],
      projectAgentNames: ["web-developer", "web-researcher"],
      projectDomains: ["web"],
      projectCategories: ["web-framework", "web-testing"],
    });
    expect(source).toContain(
      'export type SkillId = GlobalSkillId | "web-framework-react" | "web-testing-vitest"',
    );
    expect(source).toContain(
      'export type AgentName = GlobalAgentName | "web-developer" | "web-researcher"',
    );
    expect(source).toContain('export type Domain = GlobalDomain | "web"');
    expect(source).toContain(
      'export type Category = GlobalCategory | "web-framework" | "web-testing"',
    );
  });

  it("extends global types with mixed-scope items (full config passed)", () => {
    // When the full config includes both global and project-scoped items,
    // all items should appear as explicit union extensions
    const source = generateProjectConfigTypesSource({
      globalTypesImportPath: "../../.claude-src",
      projectSkillIds: ["web-framework-react", "project-custom-skill"],
      projectAgentNames: ["web-developer", "custom-reviewer"],
      projectDomains: ["web"],
      projectCategories: ["web-framework"],
    });
    expect(source).toContain(
      'export type SkillId = GlobalSkillId | "project-custom-skill" | "web-framework-react"',
    );
    expect(source).toContain(
      'export type AgentName = GlobalAgentName | "custom-reviewer" | "web-developer"',
    );
  });
});

describe("regenerateConfigTypes with global install", () => {
  let tempDir: string;
  let globalDir: string;
  let savedHome: string | undefined;

  beforeEach(async () => {
    tempDir = await createTempDir("cc-regen-project-types-test-");
    // A global install root the test owns, reached through HOME rather than through a
    // module-load constant. `globalInstallRoot()` reads os.homedir() at call time and the
    // setup file's spy honours an overridden HOME, so this is the same mechanism every other
    // scope-aware reader uses — where the Object.defineProperty this replaced was a second one,
    // grown around a constant that could not be moved.
    globalDir = await createTempDir("cc-regen-global-root-test-");
    savedHome = process.env.HOME;
    process.env.HOME = globalDir;
  });

  afterEach(async () => {
    if (savedHome === undefined) delete process.env.HOME;
    else process.env.HOME = savedHome;
    await cleanupTempDir(tempDir);
    await cleanupTempDir(globalDir);
  });

  it("generates project-import config-types when global exists", async () => {
    // Create the global config-types.ts so detection succeeds
    const globalClaudeSrc = path.join(globalDir, CLAUDE_SRC_DIR);
    await mkdir(globalClaudeSrc, { recursive: true });
    const globalTypesPath = path.join(globalClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    await writeFile(globalTypesPath, "// global types");

    // Create project .claude-src/
    const projectClaudeSrc = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(projectClaudeSrc, { recursive: true });

    const data = makeBackgroundData({
      "web-framework-react": SKILLS.react,
    });

    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");

    // Should have import from global, not standalone unions
    expect(content).toContain("import type {");
    expect(content).toContain("SkillId as GlobalSkillId");
    expect(content).toContain("export type SkillId = GlobalSkillId;");
    // Should NOT contain inline skill IDs from the matrix
    expect(content).not.toContain('"web-framework-react"');
  });

  it("includes project-only extras when global exists", async () => {
    const globalClaudeSrc = path.join(globalDir, CLAUDE_SRC_DIR);
    await mkdir(globalClaudeSrc, { recursive: true });
    await writeFile(path.join(globalClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS), "// global types");

    const projectClaudeSrc = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(projectClaudeSrc, { recursive: true });

    const data = makeBackgroundData({});

    await regenerateConfigTypes(tempDir, data, {
      extraSkillIds: ["acme-deploy-pipeline"],
      extraAgentNames: ["custom-reviewer"],
    });

    const configTypesPath = path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");

    expect(content).toContain("SkillId as GlobalSkillId");
    expect(content).toContain('"acme-deploy-pipeline"');
    expect(content).toContain('"custom-reviewer"');
  });

  it("narrows SelectedAgentName from the project config's agents", async () => {
    // Create global config-types.ts
    const globalClaudeSrc = path.join(globalDir, CLAUDE_SRC_DIR);
    await mkdir(globalClaudeSrc, { recursive: true });
    await writeFile(path.join(globalClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS), "// global types");

    // Create project .claude-src/ with a config whose agents are the selection
    const projectClaudeSrc = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(projectClaudeSrc, { recursive: true });

    const configContent = generateConfigSource(
      buildProjectConfig({
        agents: buildAgentConfigs(["web-developer", "api-developer"]),
      }),
    );
    await writeFile(path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TS), configContent);

    const data = makeBackgroundData({});
    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");

    // SelectedAgentName should be narrowed to the config's agents
    expect(content).toContain('export type SelectedAgentName = "web-developer" | "api-developer"');
    // Should NOT fall back to AgentName
    expect(content).not.toContain("export type SelectedAgentName = AgentName");
  });

  it("narrows ProjectAgentName to project-scoped agents from loaded config", async () => {
    const globalClaudeSrc = path.join(globalDir, CLAUDE_SRC_DIR);
    await mkdir(globalClaudeSrc, { recursive: true });
    await writeFile(path.join(globalClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS), "// global types");

    const projectClaudeSrc = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(projectClaudeSrc, { recursive: true });

    // Config with mixed scopes: web-developer global, api-developer project
    const configContent = generateConfigSource(
      buildProjectConfig({
        agents: [
          ...buildAgentConfigs(["web-developer"], { scope: "global" }),
          ...buildAgentConfigs(["api-developer"], { scope: "project" }),
        ],
      }),
    );
    await writeFile(path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TS), configContent);

    const data = makeBackgroundData({});
    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");

    // ProjectAgentName should be narrowed to only project-scoped agent
    expect(content).toContain('export type ProjectAgentName = "api-developer"');
    // Should NOT fall back to SelectedAgentName
    expect(content).not.toContain("export type ProjectAgentName = SelectedAgentName");
    // SelectedAgentName should still span both scopes
    expect(content).toContain('export type SelectedAgentName = "web-developer" | "api-developer"');
  });

  it("falls back ProjectAgentName to SelectedAgentName when all agents are global", async () => {
    const globalClaudeSrc = path.join(globalDir, CLAUDE_SRC_DIR);
    await mkdir(globalClaudeSrc, { recursive: true });
    await writeFile(path.join(globalClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS), "// global types");

    const projectClaudeSrc = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(projectClaudeSrc, { recursive: true });

    // Config with all global-scoped agents (simulates global init)
    const configContent = generateConfigSource(
      buildProjectConfig({
        agents: buildAgentConfigs(["web-developer", "web-researcher"], { scope: "global" }),
      }),
    );
    await writeFile(path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TS), configContent);

    const data = makeBackgroundData({});
    await regenerateConfigTypes(tempDir, data);

    const configTypesPath = path.join(projectClaudeSrc, STANDARD_FILES.CONFIG_TYPES_TS);
    const content = await readFile(configTypesPath, "utf-8");

    // ProjectAgentName should fall back to SelectedAgentName (all agents are global)
    expect(content).toContain("export type ProjectAgentName = SelectedAgentName");
  });
});

/**
 * The standalone branch of `regenerateConfigTypes` must narrow its unions to the
 * config sitting beside the file it is writing.
 *
 * This is the branch the `new skill` and `new agent` home legs take: at $HOME
 * `isProjectScope` is false, so no global config-types.ts is looked for and the
 * writer falls straight through to `generateConfigTypesSource(matrix, ...)` —
 * called WITHOUT the `config` argument that exists precisely to narrow the
 * unions. The result is a global `config-types.ts` whose `SkillId` union is the
 * entire marketplace matrix rather than the skills actually installed, so the
 * generated types accept ids that resolve to nothing and stop being the
 * hand-edit guard they exist to be.
 *
 * These specs drive that branch by leaving HOME alone: the setup file points
 * `os.homedir()` at an empty per-file temp directory, so `getGlobalConfigTypesPath()`
 * finds no global config-types.ts, returns null, and the writer takes the identical
 * `else` branch a $HOME call takes. Everything from `generateConfigTypesSource`
 * onward is byte-for-byte the same code.
 *
 * The `extras` assertions are not decoration: `new skill` / `new agent` pass the
 * just-created id as an extra precisely because it is not in the config yet, so
 * narrowing must keep extras and drop only what neither the config nor the
 * extras name.
 *
 * CURRENTLY RED, deliberately.
 */
describe("regenerateConfigTypes — standalone unions narrow to the on-disk config", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir("cc-regen-narrow-test-");
  });

  afterEach(async () => {
    await cleanupTempDir(tempDir);
  });

  it("omits a matrix skill the on-disk config does not install, and keeps the just-created one", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });
    await writeFile(
      path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TS),
      generateConfigSource(
        buildProjectConfig({
          skills: buildSkillConfigs(["web-framework-react"], { scope: "global" }),
          agents: buildAgentConfigs(["web-developer"], { scope: "global" }),
        }),
      ),
    );

    // The matrix carries a second skill the config does not install — the one
    // narrowing has to drop.
    const data = makeBackgroundData(
      { "web-framework-react": SKILLS.react, "api-framework-hono": SKILLS.hono },
      ["web-developer"],
    );

    await regenerateConfigTypes(tempDir, data, { extraSkillIds: ["acme-deploy-pipeline"] });

    const content = await readFile(
      path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS),
      "utf-8",
    );

    expect(content, "an installed skill must stay in the union").toContain('"web-framework-react"');
    expect(content, "the just-created skill must be added to the union").toContain(
      '"acme-deploy-pipeline"',
    );
    expect(
      content,
      "a matrix skill the config does not install must not appear in the union",
    ).not.toContain('"api-framework-hono"');
  });

  it("omits an agent definition the on-disk config does not install, and keeps the just-created one", async () => {
    const claudeSrcDir = path.join(tempDir, CLAUDE_SRC_DIR);
    await mkdir(claudeSrcDir, { recursive: true });
    await writeFile(
      path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TS),
      generateConfigSource(
        buildProjectConfig({
          skills: buildSkillConfigs(["web-framework-react"], { scope: "global" }),
          agents: buildAgentConfigs(["web-developer"], { scope: "global" }),
        }),
      ),
    );

    // The agent definitions carry a second agent the config does not install.
    const data = makeBackgroundData({ "web-framework-react": SKILLS.react }, [
      "web-developer",
      "api-developer",
    ]);

    await regenerateConfigTypes(tempDir, data, { extraAgentNames: ["custom-reviewer"] });

    const content = await readFile(
      path.join(claudeSrcDir, STANDARD_FILES.CONFIG_TYPES_TS),
      "utf-8",
    );

    expect(content, "an installed agent must stay in the union").toContain('"web-developer"');
    expect(content, "the just-created agent must be added to the union").toContain(
      '"custom-reviewer"',
    );
    expect(
      content,
      "an agent definition the config does not install must not appear in the union",
    ).not.toContain('"api-developer"');
  });
});

/**
 * `ConfigTypesBackgroundData` is the union inputs every config-types.ts writer derives its
 * literals from, and it had THREE producers computing the same two lines: `typesDataFor`
 * (`config-gate/pair-writer.ts`), `buildConfigTypesBackgroundData` (`config-gate/propagate.ts`)
 * and an inline block inside a third that loaded for itself and that no command reached.
 *
 * Closing two of the three would leave the shape that produced them: two producers that agree
 * make the third look rigorous while it drifts, which is the mixed-matcher defect CLAUDE.md
 * names. So the constructor lives once, beside the type, and the roster below is the gate —
 * every production module that names the type or its derived field is listed with the posture it
 * takes, and the roster is asserted against a walk of `src/cli`. A fourth producer reddens this
 * file and its author has to say which side it is on.
 */
describe("buildConfigTypesBackgroundData", () => {
  const CUSTOM_AGENT_DEFS: Partial<Record<AgentName, AgentDefinition>> = {
    [AGENT_DEFS.webDev.name]: createMockAgent(AGENT_DEFS.webDev.title),
    [AGENT_DEFS.apiDev.name]: createMockAgent(AGENT_DEFS.apiDev.title, { custom: true }),
  };

  it("rosters every sub-agent it is handed", () => {
    expect(
      buildConfigTypesBackgroundData(EMPTY_MATRIX, CUSTOM_AGENT_DEFS).agentNames,
    ).toStrictEqual([AGENT_DEFS.webDev.name, AGENT_DEFS.apiDev.name]);
  });

  it("names as custom exactly the ones whose definition carries the flag", () => {
    expect(
      buildConfigTypesBackgroundData(EMPTY_MATRIX, CUSTOM_AGENT_DEFS).customAgentNames,
      "the custom set drives the // Custom section comment in the emitted AgentName union",
    ).toStrictEqual([AGENT_DEFS.apiDev.name]);
  });

  it("carries the matrix through untouched, because it derives nothing from it", () => {
    expect(buildConfigTypesBackgroundData(EMPTY_MATRIX, CUSTOM_AGENT_DEFS).matrix).toBe(
      EMPTY_MATRIX,
    );
  });
});

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../../..");

describe("every producer of ConfigTypesBackgroundData", () => {
  /** What a module does with the type. Only the first builds one. */
  type ProducerPosture =
    /** Declares the type and the one constructor for it. */
    | "the one constructor"
    /** Calls the constructor and reads the value; builds nothing of its own. */
    | "calls the constructor"
    /** Re-exports the type and builds nothing. */
    | "re-export only"
    /** Builds its own. Named, not tolerated silently. */
    | "its own constructor";

  type BackgroundDataReader = {
    /** Path relative to the package root. */
    file: string;
    posture: ProducerPosture;
    /** Why that posture is the right one here. */
    why: string;
  };

  const READERS = [
    {
      file: "src/cli/lib/config-gate/index.ts",
      posture: "calls the constructor",
      why: "`writeScopeConfigTypes` wraps the gate deps it already loaded and hands them to `regenerateConfigTypes`.",
    },
    {
      file: "src/cli/lib/config-gate/pair-writer.ts",
      posture: "calls the constructor",
      why: "`renderStandaloneTypes` needs the same three values to call `generateConfigTypesSource`; it built them itself as `typesDataFor` until this roster landed.",
    },
    {
      file: "src/cli/lib/config-gate/propagate.ts",
      posture: "calls the constructor",
      why: "`writeProjectConfigPair` regenerates a propagated project's types from the matrix and agents the fan-out already loaded. It declared its own `buildConfigTypesBackgroundData` until this roster landed.",
    },
    {
      file: "src/cli/lib/configuration/index.ts",
      posture: "re-export only",
      why: "The configuration barrel.",
    },
    {
      file: "src/cli/lib/configuration/config-types-writer.ts",
      posture: "the one constructor",
      why: "The type is declared here, so the constructor is too. Every producer is handed the matrix and the agent roster it builds from; none loads them for itself.",
    },
  ] as const satisfies readonly BackgroundDataReader[];

  /**
   * The two names a module must reach for to build one: the type it would annotate the value
   * with, and the one field it cannot fill without deriving something. A module naming neither
   * holds no `ConfigTypesBackgroundData`, so the walk is exhaustive over the class.
   */
  const CONSTRUCTION_TOKENS = ["ConfigTypesBackgroundData", "customAgentNames"];

  /** A spec or a test-support module: neither ships, so neither is bound by the rule. */
  function isTestSource(file: string): boolean {
    return file.includes("/__tests__/") || /\.test\.tsx?$/.test(file);
  }

  async function readSource(file: string): Promise<string> {
    return readFile(path.join(PACKAGE_ROOT, file), "utf-8");
  }

  async function productionFilesNaming(tokens: readonly string[]): Promise<string[]> {
    const files = await glob("src/cli/**/*.{ts,tsx}", PACKAGE_ROOT);
    const production = files.filter((file) => !isTestSource(file));
    const verdicts = await Promise.all(
      production.map(async (file) => {
        const source = await readSource(file);
        return tokens.some((token) => source.includes(token)) ? [file] : [];
      }),
    );
    return verdicts.flat().sort(bytewise);
  }

  it("is one of the modules rostered here, so a fourth producer cannot land unjudged", async () => {
    expect(
      await productionFilesNaming(CONSTRUCTION_TOKENS),
      "a module that builds or reads this type and is not rostered above is one nothing holds to the rule",
    ).toStrictEqual(READERS.map((reader) => reader.file).sort(bytewise));
  });

  /**
   * The half that reads the tree rather than the roster above. `agents[name]?.custom === true` is
   * the derivation itself — the one line a second constructor cannot avoid writing — so a module
   * carrying it has computed the custom set for itself whatever posture its roster row claims.
   */
  it("derives the custom set in exactly one module", async () => {
    expect(
      await productionFilesNaming(["?.custom === true"]),
      "two modules deriving which sub-agents are custom is two answers to one question",
    ).toStrictEqual(["src/cli/lib/configuration/config-types-writer.ts"]);
  });
});
