import type { Category, CategoryDefinition } from "../../types";

/**
 * Built-in category definitions, equivalent to config/skill-categories.ts.
 * Source repos may override or extend these via their own config files.
 */
export const defaultCategories = {
  "web-framework": {
    id: "web-framework",
    displayName: "Framework",
    description: "UI framework (React, Vue, Angular, SolidJS)",
    domain: "web",
    exclusive: true,
    order: 1,
  },
  "web-meta-framework": {
    id: "web-meta-framework",
    displayName: "Meta-Framework",
    description: "Full-stack meta-framework (Next.js, Remix, Nuxt, SvelteKit)",
    domain: "web",
    exclusive: true,
    order: 2,
  },
  "web-routing": {
    id: "web-routing",
    displayName: "Routing",
    description: "Client-side routing (TanStack Router)",
    domain: "web",
    exclusive: true,
    order: 3,
  },
  "web-styling": {
    id: "web-styling",
    displayName: "Styling",
    description: "CSS approach (SCSS Modules, Tailwind, CVA)",
    domain: "web",
    exclusive: false,
    order: 4,
  },
  "web-client-state": {
    id: "web-client-state",
    displayName: "Client State Management",
    description: "UI state, forms, local data (Zustand, Redux, MobX)",
    domain: "web",
    exclusive: true,
    order: 5,
  },
  "web-server-state": {
    id: "web-server-state",
    displayName: "Server State / Data Fetching",
    description: "API data caching (React Query, SWR)",
    domain: "web",
    exclusive: true,
    order: 6,
  },
  "web-graphql-client": {
    id: "web-graphql-client",
    displayName: "GraphQL Client",
    description: "GraphQL client library (Apollo Client, urql)",
    domain: "web",
    exclusive: true,
    order: 7,
  },
  "web-rpc": {
    id: "web-rpc",
    displayName: "Type-Safe RPC",
    description: "End-to-end type-safe RPC (tRPC)",
    domain: "web",
    exclusive: false,
    order: 8,
  },
  "web-forms": {
    id: "web-forms",
    displayName: "Validation",
    description: "Schema validation (Zod)",
    domain: "web",
    exclusive: false,
    order: 9,
  },
  "web-form-library": {
    id: "web-form-library",
    displayName: "Form Library",
    description: "Form state and submission (React Hook Form, TanStack Form, VeeValidate)",
    domain: "web",
    exclusive: true,
    order: 10,
  },
  "web-testing": {
    id: "web-testing",
    displayName: "Testing",
    description: "Unit, component, and visual testing",
    domain: "web",
    exclusive: false,
    order: 11,
  },
  "web-e2e": {
    id: "web-e2e",
    displayName: "E2E Testing",
    description: "End-to-end browser testing (Playwright, Cypress)",
    domain: "web",
    exclusive: true,
    order: 12,
  },
  "web-ui-kit": {
    id: "web-ui-kit",
    displayName: "Design System Kit",
    description: "Pre-styled component kit (shadcn/ui, MUI, Mantine, Vuetify)",
    domain: "web",
    exclusive: true,
    order: 13,
  },
  "web-ui-components": {
    id: "web-ui-components",
    displayName: "Headless Components",
    description: "Headless primitives (Radix UI, Base UI, Headless UI, TanStack Table)",
    domain: "web",
    exclusive: false,
    order: 14,
  },
  "web-tooling": {
    id: "web-tooling",
    displayName: "Build Tools",
    description: "Frontend build tools and bundlers (Vite, Webpack)",
    domain: "web",
    exclusive: false,
    order: 15,
  },
  "web-docs": {
    id: "web-docs",
    displayName: "Documentation Framework",
    description: "Documentation site generator (Docusaurus, VitePress)",
    domain: "web",
    exclusive: true,
    order: 16,
  },
  "web-mocking": {
    id: "web-mocking",
    displayName: "API Mocking",
    description: "Mock Service Worker for development and testing",
    domain: "web",
    exclusive: false,
    order: 17,
  },
  "web-error-handling": {
    id: "web-error-handling",
    displayName: "Error Handling",
    description: "Error boundaries, result types, and error patterns",
    domain: "web",
    exclusive: false,
    order: 18,
  },
  "web-i18n": {
    id: "web-i18n",
    displayName: "Internationalization",
    description: "i18n libraries (next-intl, react-intl, vue-i18n)",
    domain: "web",
    exclusive: true,
    order: 19,
  },
  "web-file-upload": {
    id: "web-file-upload",
    displayName: "File Upload",
    description: "File upload patterns and handling",
    domain: "web",
    exclusive: false,
    order: 20,
  },
  "web-files": {
    id: "web-files",
    displayName: "Files & Images",
    description: "Image handling and file processing",
    domain: "web",
    exclusive: false,
    order: 21,
  },
  "web-utilities": {
    id: "web-utilities",
    displayName: "Utilities",
    description: "Utility libraries (date-fns, native JS patterns)",
    domain: "web",
    exclusive: false,
    order: 22,
  },
  "web-realtime": {
    id: "web-realtime",
    displayName: "Realtime",
    description: "Bidirectional realtime (WebSockets, Socket.IO)",
    domain: "web",
    exclusive: true,
    order: 23,
  },
  "web-streaming": {
    id: "web-streaming",
    displayName: "Server Streaming",
    description: "Server-sent events and HTTP streaming",
    domain: "web",
    exclusive: false,
    order: 24,
  },
  "web-animation": {
    id: "web-animation",
    displayName: "Animation",
    description: "Animation libraries and CSS animations",
    domain: "web",
    exclusive: false,
    order: 25,
  },
  "web-pwa": {
    id: "web-pwa",
    displayName: "Progressive Web App",
    description: "Service workers, offline-first patterns, and PWA features",
    domain: "web",
    exclusive: false,
    order: 26,
  },
  "web-accessibility": {
    id: "web-accessibility",
    displayName: "Accessibility",
    description: "WCAG compliance, ARIA, and keyboard navigation",
    domain: "web",
    exclusive: false,
    order: 27,
  },
  "web-performance": {
    id: "web-performance",
    displayName: "Web Performance",
    description: "Bundle optimization, render performance, and code splitting",
    domain: "web",
    exclusive: false,
    order: 28,
  },
  "web-3d": {
    id: "web-3d",
    displayName: "3D Graphics",
    description: "3D rendering (React Three Fiber)",
    domain: "web",
    exclusive: false,
    order: 29,
  },
  "web-dataviz": {
    id: "web-dataviz",
    displayName: "Data Visualization",
    description: "Charts and data visualization (D3, Recharts)",
    domain: "web",
    exclusive: false,
    order: 30,
  },
  "web-dnd": {
    id: "web-dnd",
    displayName: "Drag & Drop",
    description: "Drag-and-drop interactions (dnd-kit)",
    domain: "web",
    exclusive: false,
    order: 31,
  },
  "web-editor": {
    id: "web-editor",
    displayName: "Rich Text Editor",
    description: "Rich text editing (Lexical, Tiptap)",
    domain: "web",
    exclusive: true,
    order: 32,
  },
  "web-maps": {
    id: "web-maps",
    displayName: "Maps",
    description: "Interactive maps (Leaflet, Mapbox)",
    domain: "web",
    exclusive: true,
    order: 33,
  },
  "api-api": {
    id: "api-api",
    displayName: "API Framework",
    description: "Backend framework (Hono, Express, Fastify)",
    domain: "api",
    exclusive: true,
    order: 1,
  },
  "api-sql-engine": {
    id: "api-sql-engine",
    displayName: "SQL Engine",
    description: "Primary SQL engine (PostgreSQL, MySQL, CockroachDB)",
    domain: "api",
    exclusive: true,
    order: 2,
  },
  "api-orm": {
    id: "api-orm",
    displayName: "ORM / Query Builder",
    description: "Database access layer (Drizzle, Prisma, TypeORM)",
    domain: "api",
    exclusive: true,
    order: 3,
  },
  "api-document": {
    id: "api-document",
    displayName: "Document / Multi-Model Database",
    description: "Primary non-SQL store (MongoDB, Mongoose, Gel, SurrealDB)",
    domain: "api",
    exclusive: true,
    order: 4,
  },
  "api-kv": {
    id: "api-kv",
    displayName: "Cache / KV Store",
    description: "Redis-class key-value provider (Redis, Upstash)",
    domain: "api",
    exclusive: true,
    order: 5,
  },
  "api-db-host": {
    id: "api-db-host",
    displayName: "Managed Database",
    description: "Managed database host (Neon, PlanetScale, Turso)",
    domain: "api",
    exclusive: true,
    order: 6,
  },
  "api-auth": {
    id: "api-auth",
    displayName: "Authentication",
    description: "Auth solution (Better Auth, Auth.js)",
    domain: "api",
    exclusive: true,
    order: 8,
  },
  "api-observability": {
    id: "api-observability",
    displayName: "Observability",
    description: "Logging, monitoring, error tracking",
    domain: "api",
    exclusive: false,
    order: 9,
  },
  "api-analytics": {
    id: "api-analytics",
    displayName: "Analytics",
    description: "Product analytics and tracking",
    domain: "api",
    exclusive: false,
    order: 10,
  },
  "api-email": {
    id: "api-email",
    displayName: "Email",
    description: "Transactional email (Resend, Sendgrid)",
    domain: "api",
    exclusive: false,
    order: 11,
  },
  "ai-provider": {
    id: "ai-provider",
    displayName: "AI Provider",
    description: "AI model provider SDKs (Anthropic, OpenAI, Google, etc.)",
    domain: "ai",
    exclusive: false,
    order: 1,
  },
  "ai-orchestration": {
    id: "ai-orchestration",
    displayName: "AI Orchestration",
    description: "Multi-model AI workflow frameworks (LangChain, LlamaIndex, Vercel AI)",
    domain: "ai",
    exclusive: false,
    order: 2,
  },
  "ai-observability": {
    id: "ai-observability",
    displayName: "AI Observability",
    description: "LLM monitoring, evaluation, and tracing (Langfuse, Promptfoo)",
    domain: "ai",
    exclusive: false,
    order: 3,
  },
  "ai-infrastructure": {
    id: "ai-infrastructure",
    displayName: "AI Infrastructure",
    description: "Model hosting, serving, and inference gateways",
    domain: "ai",
    exclusive: false,
    order: 4,
  },
  "ai-patterns": {
    id: "ai-patterns",
    displayName: "AI Patterns",
    description: "Cross-cutting AI usage patterns (tool use, prompting)",
    domain: "ai",
    exclusive: false,
    order: 5,
  },
  "api-baas": {
    id: "api-baas",
    displayName: "Backend as a Service",
    description: "Full backend platform — auth, database, storage, functions (Supabase, Firebase)",
    domain: "api",
    exclusive: true,
    order: 7,
  },
  "api-performance": {
    id: "api-performance",
    displayName: "Performance",
    description: "API performance patterns and optimization",
    domain: "api",
    exclusive: false,
    order: 12,
  },
  "api-cms": {
    id: "api-cms",
    displayName: "CMS",
    description: "CMS platforms (Payload, Sanity, Strapi)",
    domain: "api",
    exclusive: true,
    order: 13,
  },
  "api-commerce": {
    id: "api-commerce",
    displayName: "Commerce",
    description: "Commerce platforms (Stripe)",
    domain: "api",
    exclusive: false,
    order: 14,
  },
  "api-search": {
    id: "api-search",
    displayName: "Search",
    description: "Search engines (Elasticsearch, Meilisearch)",
    domain: "api",
    exclusive: true,
    order: 15,
  },
  "api-vector-db": {
    id: "api-vector-db",
    displayName: "Vector Database",
    description: "Vector databases (Pinecone, Qdrant, Chroma, Weaviate)",
    domain: "api",
    exclusive: true,
    order: 16,
  },
  "api-caching": {
    id: "api-caching",
    displayName: "Caching",
    description: "API caching strategies and patterns",
    domain: "api",
    exclusive: false,
    order: 17,
  },
  "api-graphql": {
    id: "api-graphql",
    displayName: "GraphQL Server",
    description: "GraphQL servers (Apollo Server, Mercurius, Yoga)",
    domain: "api",
    exclusive: true,
    order: 18,
  },
  "api-messaging": {
    id: "api-messaging",
    displayName: "Messaging",
    description: "Webhooks and event-driven messaging",
    domain: "api",
    exclusive: false,
    order: 19,
  },
  "api-queue": {
    id: "api-queue",
    displayName: "Queues",
    description: "Background job queues (BullMQ)",
    domain: "api",
    exclusive: false,
    order: 20,
  },
  "api-specs": {
    id: "api-specs",
    displayName: "API Specifications",
    description: "API specification formats (OpenAPI)",
    domain: "api",
    exclusive: false,
    order: 21,
  },
  "mobile-framework": {
    id: "mobile-framework",
    displayName: "Mobile Framework",
    description: "Native mobile framework (React Native, Expo)",
    domain: "mobile",
    exclusive: false,
    order: 1,
  },
  "mobile-animation": {
    id: "mobile-animation",
    displayName: "Mobile Animation",
    description: "Native animation and gestures (Reanimated, Gesture Handler, Skia)",
    domain: "mobile",
    exclusive: false,
    order: 6,
  },
  "mobile-background": {
    id: "mobile-background",
    displayName: "Background Tasks",
    description: "Background task scheduling and execution",
    domain: "mobile",
    exclusive: false,
    order: 12,
  },
  "mobile-camera": {
    id: "mobile-camera",
    displayName: "Camera",
    description: "Camera integration (Vision Camera)",
    domain: "mobile",
    exclusive: false,
    order: 10,
  },
  "mobile-deep-linking": {
    id: "mobile-deep-linking",
    displayName: "Deep Linking",
    description: "Deep links and universal/app links",
    domain: "mobile",
    exclusive: false,
    order: 9,
  },
  "mobile-deployment": {
    id: "mobile-deployment",
    displayName: "Deployment",
    description: "App builds and store releases (EAS)",
    domain: "mobile",
    exclusive: false,
    order: 15,
  },
  "mobile-hardware": {
    id: "mobile-hardware",
    displayName: "Hardware",
    description: "Device hardware access (BLE, NFC)",
    domain: "mobile",
    exclusive: false,
    order: 11,
  },
  "mobile-navigation": {
    id: "mobile-navigation",
    displayName: "Navigation",
    description: "Screen navigation (Expo Router, React Navigation)",
    domain: "mobile",
    exclusive: true,
    order: 2,
  },
  "mobile-notifications": {
    id: "mobile-notifications",
    displayName: "Notifications",
    description: "Push and local notifications",
    domain: "mobile",
    exclusive: false,
    order: 8,
  },
  "mobile-performance": {
    id: "mobile-performance",
    displayName: "Mobile Performance",
    description: "React Native performance optimization",
    domain: "mobile",
    exclusive: false,
    order: 13,
  },
  "mobile-security": {
    id: "mobile-security",
    displayName: "Mobile Security",
    description: "Mobile app security patterns (React Native)",
    domain: "mobile",
    exclusive: false,
    order: 14,
  },
  "mobile-storage": {
    id: "mobile-storage",
    displayName: "Mobile Storage",
    description: "On-device storage and offline databases (MMKV, SQLite, WatermelonDB)",
    domain: "mobile",
    exclusive: false,
    order: 4,
  },
  "mobile-styling": {
    id: "mobile-styling",
    displayName: "Mobile Styling",
    description: "Native styling (NativeWind, Unistyles)",
    domain: "mobile",
    exclusive: true,
    order: 3,
  },
  "mobile-testing": {
    id: "mobile-testing",
    displayName: "Mobile Testing",
    description: "Mobile E2E testing (Detox, Maestro)",
    domain: "mobile",
    exclusive: false,
    order: 7,
  },
  "mobile-ui-components": {
    id: "mobile-ui-components",
    displayName: "Mobile UI Components",
    description: "Native UI component libraries (React Native Paper, Tamagui)",
    domain: "mobile",
    exclusive: true,
    order: 5,
  },
  "shared-monorepo": {
    id: "shared-monorepo",
    displayName: "Monorepo",
    description: "Workspace management (pnpm workspaces)",
    domain: "shared",
    exclusive: false,
    order: 1,
  },
  "shared-task-runner": {
    id: "shared-task-runner",
    displayName: "Task Runner",
    description: "Monorepo task orchestration (Turborepo, Nx)",
    domain: "shared",
    exclusive: true,
    order: 2,
  },
  "shared-lint": {
    id: "shared-lint",
    displayName: "Lint & Format",
    description: "Linting and formatting (Biome, ESLint & Prettier)",
    domain: "shared",
    exclusive: true,
    order: 3,
  },
  "shared-tooling": {
    id: "shared-tooling",
    displayName: "Build Tooling",
    description: "TypeScript config, git hooks, changesets, stack detection",
    domain: "shared",
    exclusive: false,
    order: 4,
  },
  "shared-security": {
    id: "shared-security",
    displayName: "Security",
    description: "Authentication security patterns and best practices",
    domain: "shared",
    exclusive: false,
    order: 5,
  },
  "meta-reviewing": {
    id: "meta-reviewing",
    displayName: "Code Review",
    description: "Code review patterns and methodology",
    domain: "meta",
    exclusive: false,
    order: 1,
  },
  "meta-methodology": {
    id: "meta-methodology",
    displayName: "Methodology",
    description: "Research and investigation methodology",
    domain: "meta",
    exclusive: false,
    order: 2,
  },
  "meta-design": {
    id: "meta-design",
    displayName: "Software Design",
    description: "Software design patterns and paradigms",
    domain: "meta",
    exclusive: false,
    order: 3,
  },
  "meta-planning": {
    id: "meta-planning",
    displayName: "Planning",
    description: "Specification planning frameworks per domain",
    domain: "meta",
    exclusive: false,
    order: 4,
  },
  "infra-ci-cd": {
    id: "infra-ci-cd",
    displayName: "CI/CD",
    description: "Continuous integration and deployment pipelines",
    domain: "infra",
    exclusive: false,
    order: 1,
  },
  "infra-platform": {
    id: "infra-platform",
    displayName: "Platform",
    description: "Edge compute and deployment platforms",
    domain: "infra",
    exclusive: false,
    order: 2,
  },
  "infra-config": {
    id: "infra-config",
    displayName: "Configuration",
    description: "Environment and infrastructure configuration",
    domain: "infra",
    exclusive: false,
    order: 3,
  },
  "infra-containers": {
    id: "infra-containers",
    displayName: "Containers",
    description: "Containers (Docker, Kubernetes)",
    domain: "infra",
    exclusive: false,
    order: 5,
  },
  "infra-iac": {
    id: "infra-iac",
    displayName: "Infrastructure as Code",
    description: "Infrastructure as code (Pulumi, SST, Terraform)",
    domain: "infra",
    exclusive: true,
    order: 4,
  },
  "cli-framework": {
    id: "cli-framework",
    displayName: "CLI Framework",
    description: "CLI application framework (Commander, oclif)",
    domain: "cli",
    exclusive: true,
    order: 1,
  },
  "cli-prompts": {
    id: "cli-prompts",
    displayName: "CLI Prompts",
    description: "Interactive CLI prompts (Clack)",
    domain: "cli",
    exclusive: false,
    order: 2,
  },
  "desktop-framework": {
    id: "desktop-framework",
    displayName: "Desktop Framework",
    description: "Desktop application framework (Tauri, Electron)",
    domain: "desktop",
    exclusive: true,
    order: 1,
  },
  "desktop-backend": {
    id: "desktop-backend",
    displayName: "Desktop Backend",
    description: "Desktop backend integration (Tauri)",
    domain: "desktop",
    exclusive: false,
    order: 3,
  },
  "desktop-ipc": {
    id: "desktop-ipc",
    displayName: "IPC",
    description: "Inter-process communication (Electron)",
    domain: "desktop",
    exclusive: false,
    order: 2,
  },
  "desktop-mobile": {
    id: "desktop-mobile",
    displayName: "Mobile Support",
    description: "Desktop-to-mobile platform support (Tauri)",
    domain: "desktop",
    exclusive: false,
    order: 12,
  },
  "desktop-multiwindow": {
    id: "desktop-multiwindow",
    displayName: "Multi-Window",
    description: "Multi-window management (Electron, Tauri)",
    domain: "desktop",
    exclusive: false,
    order: 5,
  },
  "desktop-packaging": {
    id: "desktop-packaging",
    displayName: "Packaging",
    description: "App packaging and distribution (Electron Forge, Tauri)",
    domain: "desktop",
    exclusive: true,
    order: 9,
  },
  "desktop-plugins": {
    id: "desktop-plugins",
    displayName: "Plugins",
    description: "Desktop plugin systems (Tauri)",
    domain: "desktop",
    exclusive: false,
    order: 11,
  },
  "desktop-security": {
    id: "desktop-security",
    displayName: "Desktop Security",
    description: "Desktop app security hardening (Electron, Tauri)",
    domain: "desktop",
    exclusive: false,
    order: 7,
  },
  "desktop-storage": {
    id: "desktop-storage",
    displayName: "Desktop Storage",
    description: "Desktop data persistence (Electron)",
    domain: "desktop",
    exclusive: false,
    order: 6,
  },
  "desktop-testing": {
    id: "desktop-testing",
    displayName: "Desktop Testing",
    description: "Desktop app testing (Electron)",
    domain: "desktop",
    exclusive: false,
    order: 8,
  },
  "desktop-ui": {
    id: "desktop-ui",
    displayName: "Desktop UI",
    description: "Desktop UI patterns (Electron)",
    domain: "desktop",
    exclusive: false,
    order: 4,
  },
  "desktop-updates": {
    id: "desktop-updates",
    displayName: "Auto-Updates",
    description: "Application auto-updates (electron-updater)",
    domain: "desktop",
    exclusive: false,
    order: 10,
  },
} as const satisfies Record<Category, CategoryDefinition>;
