Output demo.mp4

Set Shell "zsh"
Set FontSize 16
Set FontFamily "Monaspace Neon"
Set LineHeight 1.3
Set Width 1000
Set Height 1000
Set Padding 40
Set Margin 20
Set BorderRadius 8
Set WindowBar Colorful
Set WindowBarSize 40
Set TypingSpeed 80ms
Set CursorBlink true
Set Framerate 60
Set Theme { "name": "One Dark", "black": "#21252b", "red": "#e06c75", "green": "#98c379", "yellow": "#c49a2a", "blue": "#61afef", "purple": "#c678dd", "cyan": "#56b6c2", "white": "#abb2bf", "brightBlack": "#767676", "brightRed": "#e06c75", "brightGreen": "#98c379", "brightYellow": "#e5c07b", "brightBlue": "#61afef", "brightPurple": "#c678dd", "brightCyan": "#56b6c2", "brightWhite": "#abb2bf", "background": "#21252b", "foreground": "#abb2bf", "cursor": "#abb2bf", "selection": "#323844" }


Sleep 1s
Type "npx @agents-inc/cli init"
Enter
Sleep 2500ms

# -------------------------------
# STEP STACK

# select react stack
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 900ms
Enter

# -------------------------------
# STEP DOMAINS
Sleep 900ms

# select domain
Down

# select API
Sleep 600ms
Space
Sleep 600ms

Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down

# select Infrastructure
Sleep 600ms
Space
Sleep 600ms

Enter

# -------------------------------
# STEP SKILLS > WEB
Sleep 900ms

# select Client State Management > zustand
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down

Sleep 600ms
Right
Sleep 150ms
Right
Sleep 150ms
Right

Sleep 600ms
Space
Sleep 600ms

# select Server State / Data Fetching > React Query
Down

Sleep 600ms
Left

Sleep 600ms
Space
Sleep 600ms

# select Forms & Validation > zod
Down
Sleep 600ms

Left
Sleep 150ms
Left

Sleep 600ms
Space
Sleep 600ms

# select API Mocking > MSW
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down

Sleep 600ms
Space
Sleep 600ms

# select Error Handling > Error Boundaries
Down

Sleep 600ms
Space
Sleep 600ms

# select Web Performance > Frontend Performance
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down

Sleep 600ms
Space
Sleep 600ms

# press enter
Enter


# -------------------------------
# STEP SKILLS > API -- SCROLL THROUGH
Sleep 900ms

Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Down

Sleep 600ms

Enter


# -------------------------------
# STEP SKILLS > INFRA
Sleep 900ms

Right

# select CI/CD > Github Actions
Sleep 600ms
Space
Sleep 600ms

Down
Sleep 150ms
Down

# select Configuration > Environment
Sleep 600ms
Space
Sleep 600ms

Enter


# -------------------------------
# STEP SKILLS > INFRA
Sleep 900ms

Down
Sleep 150ms
Down

# select Meta Design > Expressive Typescript
Sleep 600ms
Space
Sleep 600ms

Enter


# -------------------------------
# STEP SKILLS > SHARED
Sleep 900ms

Enter


# -------------------------------
# STEP SOURCES
Sleep 900ms

Enter


# -------------------------------
# STEP AGENTS
Sleep 900ms

Enter


# -------------------------------
# STEP CONFIRM
Sleep 900ms

Enter


# -------------------------------
# POST CONFIRM
Sleep 20000ms
