import path from "path";
import { Liquid } from "liquidjs";
import {
  readFile,
  readFileOptional,
  writeFile,
  ensureDir,
  copy,
  fileExists,
  directoryExists,
} from "../../utils/fs";
import { log, verbose } from "../../utils/logger";
import { DEFAULT_BRANDING, DIRS, EJECT_SOURCE, PROJECT_ROOT, STANDARD_FILES } from "../../consts";
import { createLiquidEngine, compileAgentForPlugin } from "../compiler";
import {
  generateStackPluginManifest,
  writePluginManifest,
  getPluginManifestPath,
} from "../plugins";
import { loadSkillsByIds, loadMergedAgents } from "../loading";
import { loadStackById, resolveAgentConfigToSkills, getStackSkillIds } from "./stacks-loader";
import { resolveAgents, convertStackToCompileConfig } from "../resolver";
import { buildStackProperty } from "../configuration";
import type {
  AgentConfig,
  AgentDefinition,
  AgentName,
  CompileConfig,
  CompiledAgentData,
  PluginManifest,
  PluginSkillRef,
  ProjectConfig,
  Skill,
  SkillId,
  Stack,
} from "../../types";
import { computeStringHash, determinePluginVersion, writeContentHash } from "../versioning";
import { unique, uniqueBy } from "remeda";
import { typedEntries, typedKeys } from "../../utils/typed-object";

function hashStackConfig(stack: ProjectConfig): string {
  const stackSkillIds = stack.stack ? getStackSkillIds(stack.stack).sort() : [];
  const parts: string[] = [
    `name:${stack.name}`,
    `description:${stack.description ?? ""}`,
    `skills:${stackSkillIds.join(",")}`,
    `agents:${stack.agents
      .map((a) => a.name)
      .sort()
      .join(",")}`,
  ];
  return computeStringHash(parts.join("\n"));
}

export type StackPluginOptions = {
  stackId: string;
  outputDir: string;
  projectRoot: string;
  agentSourcePath?: string;
  /** Optional stack configuration - if provided, bypasses loading from config/stacks.ts */
  stack?: Stack;
};

export type CompiledStackPlugin = {
  pluginPath: string;
  manifest: PluginManifest;
  stackName: string;
  agents: AgentName[];
  skillPlugins: SkillId[];
  hasHooks: boolean;
};

function generateStackReadme(
  stackId: string,
  stack: ProjectConfig,
  agents: AgentName[],
  skillPlugins: SkillId[],
): string {
  const agentList = agents.map((agent) => `- \`${agent}\``).join("\n");
  const skillList = unique(skillPlugins)
    .sort()
    .map((skill) => `- \`${skill}\``)
    .join("\n");
  const skillsSection =
    skillPlugins.length > 0
      ? `## Included Skills

This stack includes the following skills:

${skillList}

`
      : "";

  return `# ${stack.name}

${stack.description || "A Claude Code stack plugin."}

## Installation

Add this plugin to your Claude Code configuration:

\`\`\`json
{
  "plugins": ["${stackId}"]
}
\`\`\`

## Agents

This stack includes the following agents:

${agentList}

${skillsSection}---

*Generated by ${DEFAULT_BRANDING.NAME} stack-plugin-compiler*
`;
}

export async function compileStackPlugin(
  options: StackPluginOptions,
): Promise<CompiledStackPlugin> {
  const { stackId, outputDir, projectRoot, agentSourcePath } = options;
  const localAgentRoot = agentSourcePath || projectRoot;

  verbose(`Compiling stack plugin: ${stackId}`);
  verbose(`  Stack/skills source: ${projectRoot}`);
  verbose(`  Local agent source: ${localAgentRoot}`);
  verbose(`  CLI agent source: ${PROJECT_ROOT}`);

  const agents = await loadMergedAgents(localAgentRoot);

  verbose(`  Loaded ${Object.keys(agents).length} merged agents (CLI + local)`);

  const newStack = options.stack || (await loadStackById(stackId, projectRoot));
  if (!newStack) {
    throw new Error(`Stack '${stackId}' not found in config/stacks.ts`);
  }
  verbose(`  Found stack: ${newStack.name}`);

  const agentSkillIds = new Set(
    typedKeys<AgentName>(newStack.agents).flatMap((agentName) => {
      const agentConfig = newStack.agents[agentName];
      return agentConfig ? resolveAgentConfigToSkills(agentConfig).map((ref) => ref.id) : [];
    }),
  );

  const stack: ProjectConfig = {
    name: newStack.name,
    description: newStack.description,
    agents: typedKeys<AgentName>(newStack.agents).map((name) => ({
      name,
      scope: "project" as const,
    })),
    skills: [...agentSkillIds].map((id) => ({
      id,
      scope: "project" as const,
      source: EJECT_SOURCE,
    })),
    stack: buildStackProperty(newStack),
  };

  const stackSkillIds = stack.stack ? getStackSkillIds(stack.stack) : [];
  const skills = await loadSkillsByIds(
    stackSkillIds.map((id) => ({ id })),
    projectRoot,
  );

  const compileConfig: CompileConfig = convertStackToCompileConfig(stackId, stack);

  const resolvedAgents = await resolveAgents(agents, skills, compileConfig, projectRoot, newStack);

  const pluginDir = path.join(outputDir, stackId);
  const agentsDir = path.join(pluginDir, "agents");

  await ensureDir(pluginDir);
  await ensureDir(agentsDir);

  const pluginSkillsDir = path.join(pluginDir, "skills");
  await ensureDir(pluginSkillsDir);

  const skillsToCopy = uniqueBy(Object.values(skills), (skill) => skill.path);
  for (const resolvedSkill of skillsToCopy) {
    const sourceSkillDir = path.join(projectRoot, resolvedSkill.path);
    const destSkillDir = path.join(pluginSkillsDir, resolvedSkill.id);

    if (await directoryExists(sourceSkillDir)) {
      await copy(sourceSkillDir, destSkillDir);
      verbose(`  Copied skill: ${resolvedSkill.id}`);
    } else {
      verbose(`  Warning: Skill directory not found: ${sourceSkillDir}`);
    }
  }

  const engine = await createLiquidEngine();

  for (const [name, agent] of typedEntries<AgentName, AgentConfig>(resolvedAgents)) {
    const output = await compileAgentForPlugin(name, agent, PROJECT_ROOT, engine);
    await writeFile(path.join(agentsDir, `${name}.md`), output);
    verbose(`  Compiled agent: ${name}`);
  }

  const compiledAgentNames = typedKeys<AgentName>(resolvedAgents);
  const uniqueSkillPlugins = unique(
    Object.values(resolvedAgents).flatMap((agent) => agent.skills.map((skill) => skill.id)),
  );

  const stackDir = path.join(projectRoot, DIRS.stacks, stackId);
  const claudeMdPath = path.join(stackDir, STANDARD_FILES.CLAUDE_MD);
  if (await fileExists(claudeMdPath)) {
    const claudeContent = await readFile(claudeMdPath);
    await writeFile(path.join(pluginDir, STANDARD_FILES.CLAUDE_MD), claudeContent);
    verbose(`  Copied ${STANDARD_FILES.CLAUDE_MD}`);
  }

  const newHash = hashStackConfig(stack);
  const { version, contentHash } = await determinePluginVersion(
    newHash,
    pluginDir,
    getPluginManifestPath,
  );

  const manifest = generateStackPluginManifest({
    stackName: stackId,
    description: stack.description,
    author: stack.author,
    version,
    keywords: undefined,
    hasAgents: true,
    hasHooks: false,
    hasSkills: true,
  });

  await writePluginManifest(pluginDir, manifest);

  await writeContentHash(pluginDir, contentHash, getPluginManifestPath);

  verbose(`  Wrote plugin.json (v${version})`);

  const readme = generateStackReadme(stackId, stack, compiledAgentNames, uniqueSkillPlugins);
  await writeFile(path.join(pluginDir, "README.md"), readme);
  verbose("  Generated README.md");

  return {
    pluginPath: pluginDir,
    manifest,
    stackName: stack.name,
    agents: compiledAgentNames,
    skillPlugins: uniqueSkillPlugins,
    hasHooks: false,
  };
}

export function printStackCompilationSummary(result: CompiledStackPlugin): void {
  log(`\nStack plugin compiled: ${result.stackName}`);
  log(`  Path: ${result.pluginPath}`);
  log(`  Agents: ${result.agents.length}`);
  for (const agent of result.agents) {
    log(`    - ${agent}`);
  }
  if (result.skillPlugins.length > 0) {
    log(`  Skills included: ${result.skillPlugins.length}`);
    for (const skill of result.skillPlugins) {
      log(`    - ${skill}`);
    }
  }
  if (result.hasHooks) {
    log("  Hooks: enabled");
  }
}
