import { describe, expect, it } from "vitest";

import { parseCompiledAgentSections } from "./compiled-agent-sections.js";

/**
 * The protocol's own prose, verbatim in shape from `src/agents/_templates/agent.liquid`.
 *
 * Every fixture below that renders the protocol carries it, because it is what separates a
 * reader from a scanner: three `### ` headings that name no skill, and a fenced
 * `skill: "[skill-id]"` demonstrating the call, which a scan for that shape reports as a
 * skill of its own.
 */
const PROTOCOL_PREAMBLE = `## Skill Activation Protocol

### Step 1 - EVALUATE

State whether each skill below is relevant.

### Step 2 - ACTIVATE

\`\`\`
skill: "[skill-id]"
\`\`\`

### Step 3 - IMPLEMENT

Only after the two steps above.

## Available Skills (Require Loading)
`;

const PLUGIN_MODE_AGENT = `---
name: web-developer
skills:
  - web-framework-react:web-framework-react
  - web-styling-tailwind:web-styling-tailwind
---
<!-- Generated by agents-inc v9.9.9 — do not edit; compile rewrites this file -->

# Web Developer Agent

<role>
You build web applications.
</role>

---

<skill_activation_protocol>
${PROTOCOL_PREAMBLE}
### web-testing-vitest
- Description: Vitest test runner
- Invoke: \`skill: "web-testing-vitest:web-testing-vitest"\`
- Use when: when working with web-testing

### web-state-zustand
- Description: Zustand stores
- Invoke: \`skill: "web-state-zustand:web-state-zustand"\`
- Use when: when working with web-client-state

</skill_activation_protocol>

---

<critical_reminders>
Check your work.
</critical_reminders>
`;

const EJECT_MODE_AGENT = `---
name: web-developer
skills:
  - web-framework-react
---
# Web Developer Agent

<skill_activation_protocol>
${PROTOCOL_PREAMBLE}
### web-testing-vitest
- Description: Vitest test runner
- Invoke: \`skill: "web-testing-vitest"\`
- Use when: when working with web-testing

</skill_activation_protocol>
`;

const MIXED_MODE_AGENT = `---
name: web-developer
skills:
  - web-framework-react:web-framework-react
  - web-styling-tailwind
---
# Web Developer Agent

<skill_activation_protocol>
${PROTOCOL_PREAMBLE}
### web-testing-vitest
- Description: Vitest test runner
- Invoke: \`skill: "web-testing-vitest:web-testing-vitest"\`
- Use when: when working with web-testing

### web-state-zustand
- Description: Zustand stores
- Invoke: \`skill: "web-state-zustand"\`
- Use when: when working with web-client-state

</skill_activation_protocol>
`;

/** The `{% else %}` arm: every skill preloaded, so no protocol renders at all. */
const NO_DYNAMIC_SKILLS_AGENT = `---
name: web-developer
skills:
  - web-framework-react:web-framework-react
---
# Web Developer Agent

<skills_note>
All skills for this agent are preloaded via frontmatter. No additional skill activation required.
</skills_note>
`;

/** No `skills:` key at all — the frontmatter block is emitted only when a preload exists. */
const NO_PRELOADED_SKILLS_AGENT = `---
name: web-developer
model: opus
---
# Web Developer Agent

<skill_activation_protocol>
${PROTOCOL_PREAMBLE}
### web-testing-vitest
- Description: Vitest test runner
- Invoke: \`skill: "web-testing-vitest:web-testing-vitest"\`
- Use when: when working with web-testing

</skill_activation_protocol>
`;

const NO_SKILLS_AT_ALL_AGENT = `---
name: web-developer
---
# Web Developer Agent

<skills_note>
All skills for this agent are preloaded via frontmatter. No additional skill activation required.
</skills_note>
`;

const NO_FRONTMATTER_AGENT = `# Web Developer Agent

<role>
You build web applications.
</role>
`;

/**
 * The template's own shape: nested partials under `<methodologies>`, the `---` horizontal
 * rules that separate its sections, a heading between playbook and output, and prose
 * demonstrating tag and heading syntax inside a fence.
 */
const STRUCTURED_AGENT = `---
name: web-developer
---
# Web Developer Agent

<role>
# Web Developer

You build web applications.
</role>

---

<methodologies>

<investigation_requirement>
## Investigate first
</investigation_requirement>

---

<anti_over_engineering>
## Keep it small
</anti_over_engineering>

</methodologies>

---

<skills_note>
All skills for this agent are preloaded via frontmatter. No additional skill activation required.
</skills_note>

---

## Workflow

\`\`\`markdown
<not_a_section>
# Not a heading either
\`\`\`

---

## Standards and Conventions

---

## Output Format

<critical_reminders>
## Check your work
</critical_reminders>
`;

describe("parseCompiledAgentSections", () => {
  describe("frontmatter", () => {
    it("parses the frontmatter block into a record", () => {
      const { frontmatter } = parseCompiledAgentSections(PLUGIN_MODE_AGENT);

      expect(frontmatter?.name).toBe("web-developer");
    });

    it("answers null when the text carries no frontmatter", () => {
      const { frontmatter, preloadedRefs } = parseCompiledAgentSections(NO_FRONTMATTER_AGENT);

      expect(frontmatter).toBeNull();
      expect(preloadedRefs).toStrictEqual([]);
    });
  });

  describe("preloadedRefs", () => {
    /**
     * `- id:id` has no space after the colon, so YAML reads it as a plain scalar rather
     * than a mapping. Reading it with the real parser is what proves that.
     */
    it("reads plugin-mode preloads as the qualified ref, in rendered order", () => {
      const { preloadedRefs } = parseCompiledAgentSections(PLUGIN_MODE_AGENT);

      expect(preloadedRefs).toStrictEqual([
        "web-framework-react:web-framework-react",
        "web-styling-tailwind:web-styling-tailwind",
      ]);
    });

    it("reads eject-mode preloads as the bare id", () => {
      const { preloadedRefs } = parseCompiledAgentSections(EJECT_MODE_AGENT);

      expect(preloadedRefs).toStrictEqual(["web-framework-react"]);
    });

    it("keeps each preload in the form it carries when the two modes are mixed", () => {
      const { preloadedRefs } = parseCompiledAgentSections(MIXED_MODE_AGENT);

      expect(preloadedRefs).toStrictEqual([
        "web-framework-react:web-framework-react",
        "web-styling-tailwind",
      ]);
    });

    it("answers an empty list when the frontmatter names no skills", () => {
      const { preloadedRefs } = parseCompiledAgentSections(NO_PRELOADED_SKILLS_AGENT);

      expect(preloadedRefs).toStrictEqual([]);
    });
  });

  describe("dynamicEntries", () => {
    /**
     * The asymmetry the whole module exists for: the heading is the bare id even in plugin
     * mode, and only the `Invoke:` line carries the ref.
     */
    it("reads a plugin-mode entry as a bare heading id and a qualified invoke ref", () => {
      const { dynamicEntries } = parseCompiledAgentSections(PLUGIN_MODE_AGENT);

      expect(dynamicEntries).toStrictEqual([
        { id: "web-testing-vitest", invokeRef: "web-testing-vitest:web-testing-vitest" },
        { id: "web-state-zustand", invokeRef: "web-state-zustand:web-state-zustand" },
      ]);
    });

    it("reads an eject-mode entry with the bare id on both lines", () => {
      const { dynamicEntries } = parseCompiledAgentSections(EJECT_MODE_AGENT);

      expect(dynamicEntries).toStrictEqual([
        { id: "web-testing-vitest", invokeRef: "web-testing-vitest" },
      ]);
    });

    it("keeps each entry's own invoke ref when the two modes are mixed", () => {
      const { dynamicEntries } = parseCompiledAgentSections(MIXED_MODE_AGENT);

      expect(dynamicEntries).toStrictEqual([
        { id: "web-testing-vitest", invokeRef: "web-testing-vitest:web-testing-vitest" },
        { id: "web-state-zustand", invokeRef: "web-state-zustand" },
      ]);
    });

    it("answers an empty list when the agent renders the skills note instead", () => {
      const { dynamicEntries } = parseCompiledAgentSections(NO_DYNAMIC_SKILLS_AGENT);

      expect(dynamicEntries).toStrictEqual([]);
    });

    /**
     * The protocol's `### Step 1 - EVALUATE` headings and its fenced `skill: "[skill-id]"`
     * demonstration both sit inside the section this reads. Pairing a heading to an
     * `Invoke:` line is what keeps them out; a scan for either shape reports them.
     */
    it("reports none of the protocol's own headings or its demonstrated invocation", () => {
      const { dynamicEntries } = parseCompiledAgentSections(NO_PRELOADED_SKILLS_AGENT);

      expect(dynamicEntries).toStrictEqual([
        { id: "web-testing-vitest", invokeRef: "web-testing-vitest:web-testing-vitest" },
      ]);
    });

    /**
     * A compiled body is separated by `---` rules, so a reader that SPLIT the frontmatter
     * off rather than replacing it hands back only the fragment between the first two
     * rules — and answers `[]` for every agent whose protocol sits past them.
     */
    it("reads a protocol sitting between two horizontal rules in the body", () => {
      const { dynamicEntries } = parseCompiledAgentSections(PLUGIN_MODE_AGENT);

      expect(dynamicEntries.map((entry) => entry.id)).toStrictEqual([
        "web-testing-vitest",
        "web-state-zustand",
      ]);
    });
  });

  describe("sectionOrder", () => {
    it("reports the top-level sections in render order and nothing nested inside them", () => {
      const { sectionOrder } = parseCompiledAgentSections(STRUCTURED_AGENT);

      expect(sectionOrder).toStrictEqual([
        "# Web Developer Agent",
        "<role>",
        "<methodologies>",
        "<skills_note>",
        "## Workflow",
        "## Standards and Conventions",
        "## Output Format",
        "<critical_reminders>",
      ]);
    });

    it("reports the protocol rather than the note when the agent has dynamic skills", () => {
      const { sectionOrder } = parseCompiledAgentSections(PLUGIN_MODE_AGENT);

      expect(sectionOrder).toStrictEqual([
        "# Web Developer Agent",
        "<role>",
        "<skill_activation_protocol>",
        "<critical_reminders>",
      ]);
    });
  });

  describe("an agent carrying no skills at all", () => {
    it("reports both sides empty", () => {
      const { preloadedRefs, dynamicEntries } = parseCompiledAgentSections(NO_SKILLS_AT_ALL_AGENT);

      expect(preloadedRefs).toStrictEqual([]);
      expect(dynamicEntries).toStrictEqual([]);
    });
  });
});
